### ISSUE TITLE
Add missing Clojure repl special vars (*1, *2, *3, *e) 

### ISSUE THREAD

**Issue by stephenbrady** [anmonteiro/lumo#101]
The Clojure repl implements special vars bound to the session that holds the last three results and last exception.

Documentation: https://clojure.org/reference/repl_and_main
Clojure code: https://github.com/clojure/clojure/blob/master/src/clj/clojure/main.clj#L85-L88

My testing with lumo 1.2.0 didn't find those special vars present.

**Comment by anmonteiro** [comment]
These are planned but weren't yet tracked. Thanks for raising the issue

**Comment by stephenbrady** [comment]
Great!

Awesome to have this repl - thanks!
