### ISSUE TITLE
(range) makes lumo unresponsive

### ISSUE THREAD

**Issue by aeosynth** [anmonteiro/lumo#107]
`(range)` is an infinite series, and executing it in the repl makes lumo unresponsive, and i can't kill lumo with `ctrl-c`. in node, i can kill `while (true);` with `ctrl-c`.

**Comment by mfikes** [comment]
This is generally a tough one to handle. If it helps in any way, here is how Planck checks for Ctrl-C during printing: https://github.com/mfikes/planck/commit/594df000526d2001550f5d604b21f4e32cae7814
