### ISSUE TITLE
`node` binary is actually renamed to `nodejs` under certain Ubuntus

### ISSUE THREAD

**Issue by darwin** [anmonteiro/lumo#109]
This caused `sudo npm -g install lumo-cljs` to fail:

```
...
> lumo-cljs@1.2.0 install /usr/local/lib/node_modules/lumo-cljs
> node scripts/npm_install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! not ok code 0
```

Background info:
http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu/21171188

An easy solution is to addtionally install `sudo apt-get install nodejs-legacy` or symlink `nodejs` to `node` by hand.

Opened this just in case you wanted to address it somehow. E.g. using a wrapper script instead of naked `node`.

**Comment by anmonteiro** [comment]
I pushed a small fix that should fix this. Basically we fallback to `nodejs` if `node` isn't found. Can you test?

The way to go about it is to clone Lumo, `cd packages/lumo && npm install .`

**Comment by darwin** [comment]
Works for me. Tested in Ubuntu 14.04 where it was previously failing.

**Comment by anmonteiro** [comment]
Awesome, thanks for testing
