### ISSUE TITLE
Provide options for obtaining Lumo version and bundled source

### ISSUE THREAD

**Issue by cursive-ide** [anmonteiro/lumo#112]
I'd like to support Lumo in Cursive. Cursive works by indexing source, so I need a way to obtain the source bundled inside the Lumo executable to create a "Lumo SDK" for Cursive to use. After some discussion in Slack, it seems like the best idea would be to add one command-line switch accepting a directory path, which would dump all the bundled source to that directory, and another which would print the Lumo version to stdout. This will allow me to use the Lumo version to create a version-specific path for the SDK, and later to ensure that the executable version matches the SDK version in case the user has upgraded.

**Comment by atroche** [comment]
[Here's the Slack discussion](https://clojurians-log.clojureverse.org/lumo/2017-03-29.html), in case anyone's curious
