### ISSUE TITLE
TypeError: Cannot read property 'StringBuffer' of undefined

### ISSUE THREAD

**Issue by mhuebert** [anmonteiro/lumo#12]
Running this:
```
npm i google-closure-library
lumo -e "(js/require \"google-closure-library\")"
```
Results in:
```
cljs.user=> (js/require "google-closure-library")
readline.js:983
            throw err;
            ^

TypeError: Cannot read property 'StringBuffer' of undefined
    at Object.cljs.core.pr_sb_with_opts (<embedded>:1650:94)
    at Object.cljs.core.pr_str_with_opts (<embedded>:1650:332)
    at Object.cljs.core.pr_with_opts (<embedded>:1651:78)
    at Function.cljs.core.println.cljs$core$IFn$_invoke$arity$variadic (<embedded>:1659:78)
    at Object.lumo.repl.handle_repl_error (<embedded>:7802:120)
    at Object.lumo.repl.execute_text (<embedded>:7833:432)
    at Object.lumo.repl.execute_source (<embedded>:7834:391)
    at Object.lumo.repl.execute (<embedded>:7835:170)
    at Object.p [as execute] ([eval]:5:6356)
    at c ([eval]:5:11730)
```

**Comment by anmonteiro** [comment]
I'm afraid there's no solution for this one unless something is done upstream.

The ClojureScript compiler uses `goog.string.StringBuffer` (see [here](https://github.com/clojure/clojurescript/blob/d87ac45f8015485546bd5f1a2b71678e6a049584/src/main/cljs/cljs/js.cljs#L793)) internally. By requiring the Closure Library in Node, there's a [part of the bootstrap process](https://github.com/google/closure-library/blob/969c7e53decf7b6ee3b2dd14011663d0762a1e82/closure/goog/bootstrap/nodejs.js#L51) that overwrites the whole `goog` object, which doesn't seem to play nicely with the whole thing.

Is there a reason why you're trying to require the Google Closure Library? Every namespace you need should already be bundled with Lumo 🙂

**Comment by mhuebert** [comment]
Ah, I see. I'm trying to access the Closure Library dependency graph. In node, I can do this via:

```js
require("google-closure-library");
require("google-closure-library/closure/goog/deps.js");
console.log(JSON.stringify(goog.dependencies_));
```

(Maybe it's easiest to jump out of lumo and use a raw node process for this.)

**Comment by anmonteiro** [comment]
Right. I'm not even sure if it would work even if you could execute the first `require` call, given the hard dependency that ClojureScript has on the Google Closure Library.

This is because ClojureScript doesn't really use the stock Closure Library, but instead a modified version which may or may not be compatible with the one you're trying to require.

**Comment by mhuebert** [comment]
Hmm. Ok. I wonder how deep the differences go.. so far in my own brief testing, the pieces of the dependency graph I've been looking at are identical b/w the two. 

Anyway, thanks for looking into this!
