### ISSUE TITLE
Error in build API when building with source maps on

### ISSUE THREAD

**Issue by plexus** [anmonteiro/lumo#132]
Given two files (see gist: https://gist.github.com/plexus/484c003eaae3c2bd4e7753c64a6ab91e)

- `package.json`
- `src/birch/core.cljs`

First do `npm install`, then start lumo with `lumo -c src`, and try using the build API:

```
$ lumo -c src
cljs.user=> (require '[lumo.build.api :as b])
cljs.user=> (b/build "src" {:target :nodejs
       #_=>                 :optimizations :advanced
       #_=>                 :output-to "birch-compiled.js"
       #_=>                 :main 'birch.core})
```

This works fine, but with source maps enabled:

```
cljs.user=> (b/build "src" {:target :nodejs
       #_=>                 :optimizations :advanced
       #_=>                 :output-to "birch-compiled.js"
       #_=>                 :source-map "birch-compiled.js.map"
       #_=>                 :output-dir "out"
       #_=>                 :main 'birch.core})
```

You get this:

```
#error {:message "failed compiling file:out/cljs/core.cljs", :data {:file "out/cljs/core.cljs"}, :cause #error {:message "failed compiling file:out/cljs/nodejs.cljs", :data {:file "out/cljs/nodejs.cljs"}, :cause #error {:message "Could not parse ns form cljs.nodejs", :data {:tag :cljs/analysis-error}, :cause #error {:message "failed compiling file:/home/arne/LambdaIsland/Episodes/command_line_tools_with_lumo/src/birch/core.cljs", :data {:file "/home/arne/LambdaIsland/Episodes/command_line_tools_with_lumo/src/birch/core.cljs"}, :cause #error {:message "Could not analyze dep cljs.nodejs", :data {:tag :cljs/analysis-error}, :cause #error {:message "Could not analyze dep clojure.string", :data {:tag :cljs/analysis-error}, :cause #error {:message "Could not parse ns form birch.core", :data {:tag :cljs/analysis-error}, :cause #object[Error Error: java.lang.RuntimeException: java.lang.RuntimeException: com.google.gwt.core.client.JavaScriptException: (ReferenceError) : window is not defined]}}}}}}}
```

It's not always this exact message, but it seems to always be something that's not defined.

e.g.

```
#error {:message "failed compiling file:out/cljs/core.cljs", :data {:file "out/cljs/core.cljs"}, :cause #error {:message "failed compiling file:out/cljs/nodejs.cljs", :data {:file "out/cljs/nodejs.cljs"}, :cause 
#error {:message "Could not parse ns form cljs.nodejs", :data {:tag :cljs/analysis-error}, :cause #error {:message "failed compiling file:/home/arne/LambdaIsland/Episodes/command_line_tools_with_lumo/src/birch/co
re.cljs", :data {:file "/home/arne/LambdaIsland/Episodes/command_line_tools_with_lumo/src/birch/core.cljs"}, :cause #error {:message "Could not analyze dep cljs.nodejs", :data {:tag :cljs/analysis-error}, :cause 
#error {:message "Could not analyze dep clojure.string", :data {:tag :cljs/analysis-error}, :cause #error {:message "Could not parse ns form birch.core", :data {:tag :cljs/analysis-error}, :cause #object[Error Er
ror: java.lang.RuntimeException: java.lang.RuntimeException: com.google.gwt.core.client.JavaScriptException: (TypeError) : p.getLineCount is not a function]}}}}}}}
```

**Comment by arichiardi** [comment]
Any hint on how to solve this? It seems like a namespace is missing completely, but not sure I am reading the error correctly.

**Comment by anmonteiro** [comment]
A namespace is not missing, it's this file here that doesn't exist: https://github.com/anmonteiro/lumo/blob/8b638b7e161a7722bffdc729eee173192e5360ec/src/cljs/bundled/lumo/compiler.cljs#L129

**Comment by mfikes** [comment]
This might be related: With recent work to add Closure Compiler support in Planck, I was encountering `p.getLineCount is not a function` whenever I would try to have it compose source maps for me. Looking at the code in `jscomp.js` you can see what appears to be a GWT compilation issue where a getter is emitted, and subsequently a property is accessed (properly).

```
(c,p.getLineCount()!=null?p.lineCount:-1
```

This is dealing with source map JSON, so no getter will exist, but the property will. I made a local revision to change that one instance of a getter to `p.lineCount`, and found another error of some sort waiting behind that one. At that point, I concluded that people must not be using this JavaScript port in order to compose source maps. Instead of tracking down a fix to contribute upstream, I reversed gears and did the composition myself using the facilities that exist in ClojureScript proper, here https://github.com/mfikes/planck/commit/54da01b1693b8917e1593d90a0ec32f5f7b9ff0d#diff-9cd6c94b68150c0325eb5ef1bb598492R23 making use of `decode-reverse`, `merge-source-maps`, and `invert-reverse-map`.

**Comment by arichiardi** [comment]
Yep it probably is related! Thanks Mike :)

I so so wish we would not need to duplicate efforts between plank and lumo... but thanks to both for your projects, amazing stuff going on.

By the way, I contributed a lumo compiler patch to serverless-cljs-plugin (wip/lumo branch), that is where I discovered the issue.

**Comment by arichiardi** [comment]
This might also be related: https://github.com/google/closure-compiler-js/issues/25#issuecomment-248762652

**Comment by mfikes** [comment]
@arichiardi If you `npm install google-closure-compiler-js` and look for `p.getLineCount` in `node_modules/google-closure-compiler-js/jscomp.js`, you'll see that the problem exists with the latest builds.

**Comment by anmonteiro** [comment]
Please read my comment above. This is not related to closure at all. Lumo is just not bundling the `core.aot.js.map` file.

While that Closure issue is valid, please refrain from adding noise to this issue. Happy to discuss that in a new ticket.

**Comment by arichiardi** [comment]
Uhm, I see it in the fileset out of `write-core-analysis-caches`:

```
│   ├── core.aot.js.map
│   ├── core.cljc
│   ├── core.cljs
│   ├── core.cljs.cache.aot._COLON_cljs.analyzer_SLASH_constants.json
│   ├── core.cljs.cache.aot._COLON_defs.json
│   ├── core.cljs.cache.aot._COLON_doc.json
│   ├── core.cljs.cache.aot._COLON_excludes.json
│   ├── core.cljs.cache.aot._COLON_externs.json
```

but it is true, at the REPL `(io/resource "cljs/core.aot.js.map")` returns `nil`.
