### ISSUE TITLE
Infinitive recursion when printing cyclic data structures

### ISSUE THREAD

**Issue by darwin** [anmonteiro/lumo#136]
I think you should set `*print-level*` or some equivalent in `fipp`.

```
> lumo
Lumo 1.4.0
ClojureScript 1.9.521
Node.js v7.9.0
 Docs: (doc function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> goog/global
^C

cljs.user=> #object[RangeError RangeError: Invalid string length]
```

```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F60a
```

**Comment by anmonteiro** [comment]
We pass `*print-length*` and `*print-level*` (which is what I think you're looking for) to Fipp, so you can set them at the REPL before printing a cyclic data structure.

Lumo respects whatever defaults exist in ClojureScript (in this case, `nil` for both those vars), it's your responsibility to set the variables in your session.

**Comment by arichiardi** [comment]
What if we implement something like `unravel` ellipsis navigation for this? See [usage](https://github.com/pesterhazy/unravel/blob/master/README.md#usage)
