### ISSUE TITLE
Binding to *pprint-results* not respected

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#139]
Hi Antonio, first of all thanks for adding this feature, it is going to be super useful in `inf-clojure`.

Second, I tried it in the repl (master) and it looks like it is not 100% correct yet:

```
cljs.user=> (binding [lumo.repl/*pprint-results* false] (range 0 20)) 
(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19) ;; maybe it is not pprinted here
cljs.user=> (binding [lumo.repl/*pprint-results* false] (range 0 30)) 
(0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29)
```

Wanted to raise the flag ;)

**Comment by anmonteiro** [comment]
this is expected. Bindings are not preserved across async contexts and this is especially true in self-hosted ClojureScript.
This is how you can work around it:

```clj
(set! lumo.repl/*pprint-results* false)
(range 50)
```

**Comment by arichiardi** [comment]
Got it, true this is more a ClojureScript issue I always forget.

**Comment by arichiardi** [comment]
Mmm....unfortunately this won't work in `inf-clojure` unless I always leave `lumo.repl/*pprint-results*` to `false`.
