### ISSUE TITLE
git-bash for windows: lumo-cljs/bin/lumo is not excutable

### ISSUE THREAD

**Issue by gzmask** [anmonteiro/lumo#142]
$ lumo -v
~/AppData/Roaming/npm/node_modules/lumo-cljs/bin/lumo: line 1: /lumo.exe: No such file or directory

in lumo:
"$basedir/lumo.exe"

I guess git-bash duno what $basedir is.

**Comment by gzmask** [comment]
a temporary fix will be change npm/lumo to be:
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

"$basedir/node_modules/lumo-cljs/bin/lumo.exe" "$@"
ret=$?
exit $ret

**Comment by anmonteiro** [comment]
The problem here is that the `npm/lumo` file is automatically generated by NPM. 

I remember trying to make it work with both MinGW and cmd.exe / Powershell and ultimately deciding to only support the latter as I couldn't make both work.

I'm open to any suggestions you may have.
