### ISSUE TITLE
expose `eval`

### ISSUE THREAD

**Issue by anmonteiro** [anmonteiro/lumo#146]
There are a few gotchas to keep in mind: http://blog.fikesfarm.com/posts/2016-01-22-clojurescript-eval.html

**Comment by anmonteiro** [comment]
need to take care of https://github.com/mfikes/planck/issues/288 too

**Comment by mfikes** [comment]
If this is done, it could be used to monkey-patch the use of `eval` in Spec.

https://github.com/mfikes/planck/blob/08a88c28ec7f0dd0f1ae8136fd24a364ba4309a8/planck-cljs/src/planck/repl.cljs#L780-L781

It is a hack, but useful if you are using a pre-release of `test.check` and want to `(require 'cljs.spec.test.alpha)`

**Comment by mfikes** [comment]
FWIW, Planck exposes a public `eval` in the `planck.core` namespace, with a signature that matches `clojure.core/eval`, while the variant in `planck.repl` is private and exposes the same additional arity taking an `ns` argument, facilitating internally building things like `intern`, `resolve`, and `ns-resolve`.

**Comment by anmonteiro** [comment]
Thanks, reopening to add that remaining functionality

**Comment by anmonteiro** [comment]
@moxaj do you want to put together a second PR adding the remaining functionality (public interface)?

**Comment by moxaj** [comment]
Sure, just point me to the right namespace. I see `lumo.core`, but I suspect it's not the one.

**Comment by anmonteiro** [comment]
`lumo.core` sounds good.
