### ISSUE TITLE
Install on windows not working

### ISSUE THREAD

**Issue by maacl** [anmonteiro/lumo#149]
I did a: 

    npm install -g lumo-cljs

on Windows 10, but invoking lumo at commandline results in file not found.

C:\Users\%user%\AppData\Roaming\npm is in %PATH%

I can invoke lumo using the fully qualified path to:

    C:\Users\%user%\AppData\Roaming\npm\node_modules\lumo-cljs\bin

**Comment by ScottFreeCode** [comment]
At a glance, it looks as though the `.cmd` file is hardwired to depend on Cygwin or MySys2 or some such Posix-on-Windows environment -- there are references to `/bin/sh` in both code paths. Which, besides not being obviously documented on the readme, is odd if the program itself seemingly runs fine on Node without `/bin/sh` or its Posix environment...

**Comment by anmonteiro** [comment]
Lumo on Windows is not meant to work with Cygwin. #142 is actually open to address that.

That said, I have no idea why this would be happening. Which version of Lumo are you trying to install?

**Comment by ScottFreeCode** [comment]
Installed lumo-cljs@1.4.1, and the full path method does work. Also reinstalled it and still get the same issue with reference to `/bin/sh`.

I dig a little digging and didn't come up with much, but did try installing a couple other global NPM libraries for comparison:

```txt
> grunt.cmd

@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\grunt\bin\grunt" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\grunt\bin\grunt" %*
)

> mocha.cmd

@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\mocha\bin\mocha" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\mocha\bin\mocha" %*
)

> lumo.cmd

@IF EXIST "%~dp0\/bin/sh.exe" (
  "%~dp0\/bin/sh.exe"  "%~dp0\node_modules\lumo-cljs\bin\lumo" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  /bin/sh  "%~dp0\node_modules\lumo-cljs\bin\lumo" %*
)
```

If any of this makes any difference, I'm using:
- Windows 8.1 64 bit
- Node 7.9.0 64 bit
- NPM 4.2.0
- [Corey Butler's NVM-Windows 1.1.3](https://github.com/coreybutler/nvm-windows)

**Comment by anmonteiro** [comment]
Turned out to be a regression. Fixed now, will be in the next release

**Comment by ScottFreeCode** [comment]
I learned something today! I had no idea NPM lets you use non-Node scripts as your CLI and will adjust its proxy files accordingly.

I wonder if there's a way to use NPM's lifecycle scripts to replace the placeholder file with the real one before NPM examines it to determine how to call it. But I guess as long as it's working, that's what counts, right?

**Comment by anmonteiro** [comment]
Yeah, I'm still not sure the current solution is the best. I'm leaning towards just having a `.js` wrapper script that uses the `child_process` module to spawn the Lumo binary on NPM
