### ISSUE TITLE
TypeError: (intermediate value).getFoo is not a function

### ISSUE THREAD

**Issue by jkleiser** [anmonteiro/lumo#15]
I tried to run these three lines (from http://rosettacode.org/wiki/Classes#Clojure):
```
(defprotocol Foo (getFoo [this]))
(defrecord Example1 [foo] Foo (getFoo [this] foo))
(-> (Example1. "Hi") .getFoo)
```
and I got `TypeError: (intermediate value).getFoo is not a function`.
I tried the same using real Clojure 1.8.0, but that went OK.

**Comment by anmonteiro** [comment]
This is not a bug in Lumo, but instead a difference between Clojure and ClojureScript.

Your example produces the same error in a regular (JVM) ClojureScript REPL and should be revised to:

```clojure
(defprotocol Foo (getFoo [this]))
(defrecord Example1 [foo] Foo (getFoo [this] foo))
(-> (Example1. "Hi") getFoo) ;; removed the `.`
```

**Comment by jkleiser** [comment]
That works. Thanks!
If there is a page somewhere describing the differences between Clojure and ClojureScript, then you could add a link to that page in the Lumo README.md.

**Comment by anmonteiro** [comment]
This is documented in the ClojureScript website: http://clojurescript.org/about/differences

**Comment by anmonteiro** [comment]
I don't think this belongs in the README. I'll eventually work on a Lumo user guide (in a proper website) where I can add a link to that.
