### ISSUE TITLE
Analysis error: Cannot use 'in' operator to search for ...

### ISSUE THREAD

**Issue by moxaj** [anmonteiro/lumo#160]
## Repro:

```
;; src/a/x.cljc
(ns a.x)
```

Run `lumo -c src`, `(require 'a.x)`.

## Output:

`#error {:message Could not parse ns form a.x in file a/x.cljc, :data {:tag :cljs/analysis-error}, :cause #object[TypeError TypeError: Cannot use 'in' operator to search for 'x' in a]}`

**Comment by anmonteiro** [comment]
Interesting. Upon a little investigation, seems related to the single character name in the directory (`a`)

**Comment by moxaj** [comment]
Interestingly, changing it to `b` fixes it :O

**Comment by anmonteiro** [comment]
Yeah, I found that too. it's weird and I'm looking into it.

**Comment by arichiardi** [comment]
I have seen this before. Hopefully I am not swaying from the solution but have a look at [CLJS-1982](https://dev.clojure.org/jira/browse/CLJS-1982).

**Comment by anmonteiro** [comment]
This seems related to `:static-fns true`

**Comment by anmonteiro** [comment]
I managed to repro this upstream in the ClojureScript compiler.

**Comment by anmonteiro** [comment]
So `eval` is evil. I could only figure out what the issue was by looking at the generated compiler code:
```js
cljs.core.find_ns_obj = function(a) {
  var b = cljs.core
    .munge('' + cljs.core.str.cljs$core$IFn$_invoke$arity$1(a))
    .split('.');
  cljs.core.prn.cljs$core$IFn$_invoke$arity$variadic(
    cljs.core.array_seq(['hi there', b], 0),
  );
  return cljs.core.truth_(COMPILED)
    ? cljs.core.find_ns_obj_STAR_(
        (function() {
          try {
            var a = cljs.core.first(b);
            return eval(a);
          } catch (d) {
            if (d instanceof ReferenceError)
              return cljs.core.println.cljs$core$IFn$_invoke$arity$variadic(
                cljs.core.array_seq(['errored out?', cljs.core.first(b)], 0),
              ), null;
            throw d;
          }
        })(),
        cljs.core.next(b),
        cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2('a', cljs.core.first(b)),
      )
    : cljs.core.find_ns_obj_STAR_(global, b);
};

```

**Comment by arichiardi** [comment]
Woah! That is a good catch!

**Comment by anmonteiro** [comment]
interestingly enough, without `:static-fns` this does not happen because that specific line is generated like:
```js
            return eval(cljs.core.first.call(null, b));

```

**Comment by anmonteiro** [comment]
Patch attached upstream to this ticket: https://dev.clojure.org/jira/browse/CLJS-2024

Will close this issue when we bump the ClojureScript version that includes the fix.

**Comment by anmonteiro** [comment]
this has been fixed upstream in https://github.com/clojure/clojurescript/commit/6e232445e69e3e70107a8dbfe46eb9fc6a4059e2

**Comment by anmonteiro** [comment]
Fixed by https://github.com/anmonteiro/lumo/commit/c27e645f4a0c18ed08b0c52bad463f980735097b
