### ISSUE TITLE
Lumo crashes when requireing packages with .node binary

### ISSUE THREAD

**Issue by hlolli** [anmonteiro/lumo#163]
After updating to lumo 1.5, packages that are running with .node binaries won't work, more specifically gyp built modules. In my case I'm using csound-api which requires csound and boost to be installed, but another reproduce-able example can be created if require-ing "netlinkwrapper": "1.0.0".
$ lumo
cljs.user=> (js/require "netlinkwrapper")
*crash*

These modules can be required with node 7.10.0 without crash.

**Comment by anmonteiro** [comment]
@hlolli Sorry, this regression was introduced in [this commit](https://github.com/anmonteiro/lumo/commit/61727782e5a128c70ad4b7d4ec2c1536b30f4eca#diff-0a1425bd66240468daf4c256a411ce75), and should be a very simple fix.

Do you want to put a PR together fixing it?

**Comment by hlolli** [comment]
Yup, I will look into this. Just getting used to setting up the dev env, been waiting 2 hours for `boot dev` after deleting the binary. So in next few days, thanks for the hint.

**Comment by anmonteiro** [comment]
@hlolli `boot dev` doesn't produce a binary. If you want a binary, run `boot release`

**Comment by hlolli** [comment]
lol, so I've been waiting for nothing. ehm.. how do you start lumo without creating a binary :/ ?

**Comment by anmonteiro** [comment]
`yarn dev` will start the DEV mode Lumo: https://github.com/anmonteiro/lumo/blob/master/package.json#L21.

But this will run under an actual Node.js. To debug this particular problem you'll need to create a binary. Thankfully the fix for this issue is simple: literally revert the change I linked above.

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/7ea440ab22fe42805efb6e9a3f323eb00529a964

**Comment by kanaka** [comment]
Any chance we could get a release for this?

**Comment by anmonteiro** [comment]
I can make a release, but would a link to a nightly build suffice for your immediate needs?

**Comment by kanaka** [comment]
Yeah, that would be fine.

**Comment by anmonteiro** [comment]
@kanaka https://github.com/anmonteiro/lumo/issues/65#issuecomment-271357273

**Comment by hlolli** [comment]
This is still a problem for me from the latest Lumo nightly
```
Lumo 1.5.0
ClojureScript 1.9.562
Node.js v8.0.0
```

getting segfaults from (js/require "pacage-using-gyp-or-.node")

**Comment by hlolli** [comment]
Does not happen when I run lumo like this 
`node target/bundle.js -k lumo-cache -c target`
Need to solve the heap size problem so that I can compile lumo and see if it comes back.

**Comment by anmonteiro** [comment]
@hlolli this seems odd but I'll reopen. Can you provide the name of a package that fails to execute?

**Comment by hlolli** [comment]
My importance is with csound-api for my live-coding environment, but that requires csound to be installed. You can try requireing `"netlinkwrapper": "1.0.0"` via lumo, I get exactly the same bug.

I built lumo and the binary fails, it differentiates from the nightly build, which gives me segfault, my build just causes the terminal to freeze.

**Comment by anmonteiro** [comment]
I can repro this on Ubuntu. I think the problem might be related to Lumo being statically linked, while  the native packages are compiled with a different libc version.

**Comment by anmonteiro** [comment]
fixed in #176
