### ISSUE TITLE
Q: is there a way to bundle the script inside lumo and create a platform executable?

### ISSUE THREAD

**Issue by BrunoBonacci** [anmonteiro/lumo#175]
Hi,
I've used the nexe project to bundle a script together with the node.js vm and create a platform native executable, but I find the all process very tedious and time consuming especially because the nexe project is [undergoing a rewrite](https://gitter.im/jaredallard/nexe?at=572060349b4160fa760a3346).
Is there the possibility (or planning) to do something similar with lumo?

**Comment by anmonteiro** [comment]
That's not a goal of Lumo.

This is a bit offtopic, but if you're looking for Nexe alternatives, there are a few faster ones out there, namely:

- [Zeit's PKG](https://github.com/zeit/pkg)
- [Node Compiler](https://github.com/pmq20/node-compiler)

**Comment by BrunoBonacci** [comment]
Thanks @anmonteiro, I'll look into these.
