### ISSUE TITLE
Correctly set __dirname and __filename when running script file

### ISSUE THREAD

**Issue by metametadata** [anmonteiro/lumo#185]
Steps:

1) Create executable script in the subfolder:

```
~/dev/foo ᐅ tree
.
└── bar
    └── script.cljs

1 directory, 1 file

~/dev/foo ᐅ cat bar/script.cljs
#!/usr/bin/env lumo
(ns core.script)

(println js/__dirname)
(println js/__filename)
```

2) Execute script from the outer folder:

```
~/dev/foo ᐅ ./bar/script.cljs
```

**Actual output:**

```
.
[eval]
```

**Expected:**

```
/Users/metametadata/dev/foo/bar
/Users/metametadata/dev/foo/bar/script.cljs
```

**Comment by metametadata** [comment]
In v0.6.0 this stops working as soon as script requires some ns.

**Comment by anmonteiro** [comment]
So this is not fixed after all? Should we reopen?

**Comment by metametadata** [comment]
@anmonteiro yes, let's reopen as seem to work as expected only when there's no `:require` in script file.
