### ISSUE TITLE
Requiring cljs.core.logic

### ISSUE THREAD

**Issue by frangio** [anmonteiro/lumo#190]
Is it possible to use core.logic from lumo? I couldn't find any information about it.

**Comment by anmonteiro** [comment]
[Here](https://github.com/anmonteiro/lumo/issues/51#issuecomment-264925177)'s a generic answer on how to add dependencies to Lumo.

The next version will also support a new `-D / --dependencies` flag that accepts comma separated arguments in form of `foo/bar:1.2.3` (e.g. `org.clojure/core.logic:0.8.11`) that tells Lumo to look in the _local_ Maven repository for that dependency (not transitive).

Let me know if you still have any questions.

**Comment by arichiardi** [comment]
Closing this one because it seems inactive. Another thing to add it that not all the cljs libraries can be used with `lumo`, only some are self-host compatible.
