### ISSUE TITLE
SIGINT cannot be caught

### ISSUE THREAD

**Issue by metametadata** [anmonteiro/lumo#191]
Here's [a repo](https://github.com/metametadata/lumo-signals) for reproducing the steps in `Lumo` and `NodeJS`. I've checked the behaviour on `SIGINT`, `SIGTERM`, `SIGQUIT` and `SIGHUP` and noticed the problem only with `SIGINT`.

**Steps:**

1) Run Lumo app which listens to `SIGINT` signal: `lumo app.cljs`

2) Send `SIGINT` (e.g. by clicking `Ctrl+C` or by executing `kill -INT $!`).

**Actual:** app exits without first catching signal event.

**Expected:** app is able to intercept a signal (because `NodeJS` apps are able to catch this signal).

This feature is important for apps needing to do some cleanup before exiting. E.g. I use [signal-exit](https://github.com/tapjs/signal-exit) module to do cleanup.

**Comment by anmonteiro** [comment]
thanks for the report. this may be a consequence of adding the ability to kill infinite loops with `ctrl+c` (https://github.com/anmonteiro/lumo/commit/6b1b5a15dd455c7015f2a310cb7ceb323b2b741d).
We may have to run pending SIGINT handlers or something.

**Comment by anmonteiro** [comment]
@metametadata can you repro this on a Lumo version < 1.4, e.g. 1.2 or 1.3

**Comment by metametadata** [comment]
Yes, look like a regression as it works in 1.3.0 as expected:

```
~/Dropbox/dev/lumo-signals (master ✘)✭ ᐅ lumo --version
1.5.0
~/Dropbox/dev/lumo-signals (master ✘)✭ ᐅ lumo app.cljs 
Hello
^C

~/Dropbox/dev/lumo-signals (master ✘)✭ ᐅ ./lumo --version
1.3.0
~/Dropbox/dev/lumo-signals (master ✘)✭ ᐅ ./lumo app.cljs 
Hello
^Csignal-exit: nil "SIGINT"
```

**Comment by anmonteiro** [comment]
Turns out this is actually fixed in master. Please reopen if still an issue.

**Comment by metametadata** [comment]
Thank you, looking forward to the next release!

**Comment by metametadata** [comment]
In v0.6.0 the issue is still reproducible, but only when some ns is required in the script. E.g.:

```
#!/usr/bin/env lumo
(ns core.app
  (:require [clojure.string :as str])  ; <--------- this line breaks catching of Ctrl+C
) 

(.log js/console "Hello")

(def on-exit (js/require "signal-exit"))
(on-exit (fn [code signal]
             (.log js/console "signal-exit:" (pr-str code) (pr-str signal))))

(js/setTimeout #(.log js/console "Bye")
               30000)
```

**Comment by mnewt** [comment]
It looks like this issue is happening no matter what. I see the same behavior whether at the REPL or in a script. When ctrl-c is pressed, lumo exits without ever calling the SIGINT handler.

```
$ lumo --version
1.8.0-beta
$ node --version
v8.9.1
```

```
cljs.user=> (.on js/process "SIGINT" #(console.log "SIGINT received."))
#object[process [object process]]
cljs.user=> (loop [] (recur))
^C
<<<lumo exits with status code 130>>>
```
