### ISSUE TITLE
Upgrade to new CLJS

### ISSUE THREAD

**Issue by anmonteiro** [anmonteiro/lumo#192]
need to add support for the new `:fn-invoke-direct` option just like in https://github.com/mfikes/planck/commit/054e143998b0b442d320e2f0438a6a0fb6177da6

**Comment by mfikes** [comment]
If you think of a good single-letter option, let me know. I'm just using 'Z' as a placeholder for now.

**Comment by anmonteiro** [comment]
fixed 5e48e64bb43f52aec0cdcbcc7507392f4309218d. Used the option `-f / --fn-invoke-direct`
