### ISSUE TITLE
Explore paredit.js

### ISSUE THREAD

**Issue by anmonteiro** [anmonteiro/lumo#193]
Parinfer was never really meant to handle indentation

**Comment by anmonteiro** [comment]
https://github.com/rksm/paredit.js/blob/3086a8a30a29d3391c0c733a630cbdf4dcf78507/examples/ace.ext.lang.paredit.js#L152-L155

**Comment by shaunlebron** [comment]
paredit and parinfer were both fixed for indenting unbalanced code:

- paredit: https://runkit.com/shaunlebron/5956863fd1d50b001a91fefa
- parinfer: https://runkit.com/shaunlebron/5957daaa23798b0012df7630
