### ISSUE TITLE
Lack of OpenSSL support breaks some Node.js modules

### ISSUE THREAD

**Issue by rads** [anmonteiro/lumo#2]
Thanks for your great work. Just a note: I tried to test out Lumo with [hyperlog](https://github.com/mafintosh/hyperlog) and got this error:

```
cljs.user=> (def hyperlog (js/require "hyperlog"))
Error: Node.js is not compiled with openssl crypto support
```

**Comment by mhuebert** [comment]
Same here. I tried building a version of lumo locally, as I have openssl installed, but see the same error.

**Comment by anmonteiro** [comment]
Thanks. This is an easy fix, we just need to delete this line https://github.com/anmonteiro/lumo/blob/master/scripts/package.js#L52
In my attempts to minimize the size of the final artifact, I disabled a few things.

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/748ba8845d878f23aa4f3e4878c2afce3ff724b8
