### ISSUE TITLE
package for homebrew

### ISSUE THREAD

**Issue by jab** [anmonteiro/lumo#20]
Would be cool if homebrew users could `brew install lumo`. The instructions for adding a new homebrew formula are [here](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#basic-instructions). Opening this in case anyone wants to beat me to it.

**Comment by anmonteiro** [comment]
This is planned but I haven't had the time to do it yet. We might want to track this in #9, this looks like a duplicate?

**Comment by jab** [comment]
Sorry, didn't see #9. Closing as merge and will follow progress over there. Thanks!
