### ISSUE TITLE
Can't install lumo with npm on os X

### ISSUE THREAD

**Issue by mattbishop** [anmonteiro/lumo#201]
I used npm to install lumo 1.4.1, but now 1.6.0 does not install. I did remove the old lumo version first.

```sudo npm install -g lumo-cljs
Password:
/usr/local/bin/lumo -> /usr/local/lib/node_modules/lumo-cljs/bin/lumo.js

> lumo-cljs@1.6.0 install /usr/local/lib/node_modules/lumo-cljs
> node scripts/npm_install.js || nodejs scripts/npm_install.js

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: EACCES: permission denied, open 'lumo_mac.zip'
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! lumo-cljs@1.6.0 install: `node scripts/npm_install.js || nodejs scripts/npm_install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the lumo-cljs@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mbishop/.npm/_logs/2017-07-02T18_31_59_907Z-debug.log```

**Comment by anmonteiro** [comment]
Could be just a problem with the binary download. Can you retry and let me know?

**Comment by mattbishop** [comment]
I can grab this link directly with my browser: https://github.com/anmonteiro/lumo/releases/download/1.6.0/lumo_mac.zip

**Comment by mattbishop** [comment]
Definitely fails to get the release download.

**Comment by anmonteiro** [comment]
@mattbishop I just installed 1.6.0 on my Mac through NPM with no problem.

I suppose sometimes the download fails and the installation can't proceed. Mind running `npm uninstall -g lumo-cljs` and trying to install again?

**Comment by mattbishop** [comment]
Are you using `sudo`?

**Comment by anmonteiro** [comment]
Not using sudo

**Comment by mattbishop** [comment]
All right I fixed this by updating the perms in my /usr/local/lib/node_modules from root to myself.

**Comment by anmonteiro** [comment]
Awesome. Do you think we should do more to help with this use case as part of the installation script?

**Comment by mattbishop** [comment]
Well my problem was I set up node with sudo a long time ago using MacPorts. I switched to my own installs for node things and this was a leftover from that time. 

I suppose you could error out about not being able to retrieve or save the binary but I don't know how common that would be.
