### ISSUE TITLE
Lumo cannot allocate more than 1.5GB (on 64bit machine)

### ISSUE THREAD

**Issue by mgerlach-klick** [anmonteiro/lumo#218]
Nodejs has a well-documented heap limit of 1.5GB (on 64 bit machines). The way around this is to specify the `--max_old_space_size=NEWLIMIT` command line argument for node, but this doesn't work for lumo, nor does the suggested solution of 
```
(def v8 (js/require "v8"))
(.setFlagsFromString v8 "--max_old_space_size=8192")
```

I am running into this issue when working with large-ish (~60mb) CSV files.

**Comment by anmonteiro** [comment]
We can set a better default when compiling Lumo. I'm thinking that 8192 should be enough for most use cases.

Thoughts?

**Comment by thosmos** [comment]
I just ran out of heap while attempting to load this huge 189mb json file: `https://github.com/zemirco/sf-city-lots-json` and then convert it into cljs data with the following line: `(count (js->clj  (js/JSON.parse  (lumo.io/slurp "citylots.json"))))`  I'm guessing that a more lazy method would help for something like this.

**Comment by mgerlach-klick** [comment]
FWIW I ended up working around this issue by compiling my lumo script to JS (using shadow-cljs), and then running it "manually" using node and giving it the --max_old_space_size=8192 parameter @thosmos

**Comment by arichiardi** [comment]
I hit this too, did anybody tried the proposed fix? Should we raised the `--max-old-space-size` ?
Things seem to have been worse with node 9

**Comment by filipesilva** [comment]
Node 12 generally does away with this requirement on Node's side. When using it, it's better to not set any default.

**Comment by anmonteiro** [comment]
@filipesilva what does that mean exactly? Node.js 12 doesn't need `--max-old-space-size` anymore?

If that's the case this issue can be closed as I've upgraded Node.js to v12 in master.

**Comment by filipesilva** [comment]
The important bit can be found in https://medium.com/@nodejs/introducing-node-js-12-76c41a1b3f3f:

> Properly configure default heap limits
> This update will configure the JavaScript heap size based on available memory instead of using defaults that were set by V8 for use with browsers. In previous releases, unless configured, V8 defaulted to limiting the max heap size to 700 MB or 1400MB on 32 and 64-bit platforms respectively. Configuring the heap size based on available memory ensures that Node.js does not try to use more memory than is available and terminating when its memory is exhausted.
> This is particularly useful when processing large data-sets. As before, it will still be possible to set — max-old-space-size to use a different limit if the default is not appropriate for your application.

The end result is that Node 12 won't need `--max-old-space-size` because it will try to use a default that matches your available memory.

**Comment by anmonteiro** [comment]
Awesome. This will be in the next release then. Closing.

**Comment by anmonteiro** [comment]
If anybody wants to PR an entry to the Changelog I’d be happy to merge.

**Comment by filipesilva** [comment]
PR for the changelog up at https://github.com/anmonteiro/lumo/pull/481
