### ISSUE TITLE
Cannot npm/yarn install from master - opencollective not found

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#241]
Hello Antonio,

I am opening this issue because I think the `postinstall` task is breaking this at the moment:

```
$ yarn add https://github.com/anmonteiro/lumo#master --dev
1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
⠁ 
⠁ 
⠁ 
⠁ 
error /home/arichiardi/git/cqrs-cloud/node_modules/lumo: Command failed.
Exit code: 127
Command: sh
Arguments: -c opencollective postinstall
Directory: /home/arichiardi/git/cqrs-cloud/node_modules/lumo
Output:
sh: 1: opencollective: not found
```

Shall I open a PR with a change from `"postinstall": "opencollective postinstall"` to `"postinstall": "./node_modules/.bin/opencollective postinstall"`?

Thanks a lot!

**Comment by arichiardi** [comment]
After Slack's conversation, `lumo` cannot/should not be installed this way. Closing.

**Comment by dannydulai** [comment]
@arichiardi , you decided that lumo can not be installed with yarn?

**Comment by anmonteiro** [comment]
@dannydulai that's not the issue at hand. It's not supported to install Lumo from Git e.g. `npm install github:anmonteiro/lumo`.

It should be possible to install Lumo with Yarn

**Comment by arichiardi** [comment]
Yep not supported at the moment, in any case it would require downloading and compiling node along.
