### ISSUE TITLE
Ns form require of npm dependencies does not seem to work

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#244]
Hi Antonio!

Sorry for bombing :bomb:  Just wanted to report something that you might know already.

Basically I tried to compile a namespace using the new syntax:

```
(ns my.util
  (:require [lodash.camelcase :as lcamelcase]))
```

No success. The old-style `(js/require "lodash.camelcase")`, works well.

Just putting it out there for other folks who might come across this problem.

Thanks as usual for your work on both ClojureScript and `lumo`!

**Comment by anmonteiro** [comment]
This is not supported in Lumo yet

**Comment by anmonteiro** [comment]
BTW this works fine at the REPL, it's just not supported when compiling projects with Lumo.
