### ISSUE TITLE
Using /usr/bin/env & command line arguments

### ISSUE THREAD

**Issue by dotemacs** [anmonteiro/lumo#247]
When using something like this

```clojure
#!/usr/bin/env lumo
;; -*- clojure -*-

(println *command-line-args*)

(def process (js/require "process"))
(def args (.slice (.-argv process) 3))

(doseq [arg args]
  (println arg))
```

And then when I invoke it as:

`./script.cljs foo bar baz`

I'll get the following output:
```
nil
foo
bar
baz
```

You can see that I can get to the command line arguments via `process` but the arguments are not to be found in `*command-line-arguments*`.

**Comment by anmonteiro** [comment]
Fixed in #237
