### ISSUE TITLE
Getting arglists from the runtime environment

### ISSUE THREAD

**Issue by hlolli** [anmonteiro/lumo#248]
I can have a look at this during the week, but it would be nice if the arglists can be more dynamic, as can be seen in this following code. This would make it more nice to use with inf-clojure and/or other IDE's.

```
dev.cusco-2017=> (defn fun [arg1 arg2] (+ arg1 arg2))
#'dev.cusco-2017/fun
dev.cusco-2017=> (lumo.repl/get-arglists "fun")
nil
dev.cusco-2017=> (lumo.repl/get-arglists "reduce")
([f coll] [f val coll])
```

**Comment by mfikes** [comment]
A workable solution appears to involve injecting `:ns :name` into the env map. See https://github.com/mfikes/planck/commit/9f75ce29f9cbe311db2e66fd45049d20e2b8e186

**Comment by mfikes** [comment]
This tweak to the above make the code closer to what you see in `cljs.js` and pretty much identical to an expression in `cljs.analyzer/resolve-symbol` https://github.com/mfikes/planck/commit/c0ea406e85c7b4ebf696c0cb71da82e6334e08e0
