### ISSUE TITLE
Missing cljs.repl/doc

### ISSUE THREAD

**Issue by pesterhazy** [anmonteiro/lumo#26]
`doc` is useful for working from the REPL (http://cljs.github.io/api/cljs.repl/doc) but it's not included yet:

```
cljs.user=> (require 'cljs.repl)
#error {:message No such namespace: cljs.repl, could not locate cljs/repl.cljs, cljs/repl.cljc, or Closure namespace "cljs.repl", :data {:tag :cljs/analysis-error}}
```

Same for `cljs.repl/source`.

The fns should be automatically interned in the REPL, as they are in clojure repls.

**Comment by anmonteiro** [comment]
We won't be able to support `cljs.repl` because that namespace isn't bootstrap ClojureScript compatible. I think we'll have to implement our own `doc` REPL specials like Planck does it

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/1a762d175b056bb6d48f9e21d7f40e23d93bef5f
