### ISSUE TITLE
remove #_=> from pasted code

### ISSUE THREAD

**Issue by anmonteiro** [anmonteiro/lumo#261]

**Comment by arichiardi** [comment]
This is a tough one, it seems paredit analyzes the input line by line, which of course is not a balanced expression and therefore outputs `#_=>`.

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/8f2b2e786a531c05b982c4a460089f8224efc20f

**Comment by arichiardi** [comment]
Or post process, right :smile:

**Comment by arichiardi** [comment]
This will be super good for `inf-clojure` as well, thanks!
