### ISSUE TITLE
REPL hangs on windows

### ISSUE THREAD

**Issue by anmonteiro** [anmonteiro/lumo#266]
I'm seeing the REPL hang on windows sometimes, can't get a consistent repro

**Comment by yambee** [comment]
Just installed lumo on my Win10 with npm -g, started REPL, but it closes after each evaluation session, need to rerun it every time

**Comment by Gregg8** [comment]
I have been getting this as well. Here's the simplest of sessions...
```
C:\Progs\lumo>lumo
Lumo 1.9.0
ClojureScript 1.10.439
Node.js v10.9.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (+ 1 1)
2
cljs.user=>
C:\Progs\lumo>
```
No error messages at all :-(

Sometimes it allows two commands before exiting.

This also happens with my previous versions: `1.9.0-alpha` and `1.4.1`

If it helps, `1.4.1` did work at one point and I thought it was wonderful. No idea what change I made or what Windows updates made to fowl it up (I have latest build of Win10).

Would love it to work again :-)

**Comment by filipesilva** [comment]
Seeing it too, exits after one, sometimes two evals. 

Is there anything I can do to help debug? I'm not very familiar with Clojure proper (using Lumo to learn) but I am very familiar with node.

**Comment by filipesilva** [comment]
Just tried `1.10.1` and it doesn't seem to happen anymore, not sure why. But it's great regardless!

**Comment by anmonteiro** [comment]
@filipesilva thanks. closing then

**Comment by filipesilva** [comment]
Think I spoke too soon. I see it happening again:
```
$ lumo -i src/scratch.cljs -r
Lumo 1.9.0
ClojureScript 1.10.439
Node.js v10.9.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (println "ping")
ping
nil
cljs.user=>
```
