### ISSUE TITLE
Call function from cljs file from command line

### ISSUE THREAD

**Issue by nepeckman** [anmonteiro/lumo#27]
After scripting a little with lumo, a small pain point is the inability to call a main function from the command line. The scripts must all end with imperative calls to functions, which doesn't feel right for Clojure code. Beyond style complaints, the imperative function calls have negative effects when putting multiple files on the classpath, as all the imperative function calls are made from all the files. It would be beneficial to be able to call a specific function after all the code is evaluated, either through user specification on the command line, or by convention (always call `-main` if it exits).

**Comment by anmonteiro** [comment]
this is akin to the `-m / --main` option in Planck

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/4440ab60e9a5422af62dc1396ff6251caa266e17
