### ISSUE TITLE
Turn off `:def-emits-var` if `require` at REPL

### ISSUE THREAD

**Issue by anmonteiro** [anmonteiro/lumo#271]
From @mfikes on Slack:

> Planck turns off `:def-emits-var` when processing `require` forms, specifically so that the `def`s _inside_ the required namespaces don't get processed as if at the REPL.  Hmm. OK. More to sort out on this one then.

**Comment by anmonteiro** [comment]
https://github.com/mfikes/planck/commit/fb8310bed7678d4d517e32692d079196d7846456

**Comment by mfikes** [comment]
The rationale for this is illustrated by the following concrete example. Let's say you have `src/foo/core.cljs` with contents

```clojure
(ns foo.core)

(def a 3)
```

Then do `lumo -K -c src` and at the REPL, `(require 'foo.core)`.

For Planck, you would get `.planck_cache/foo_SLASH_core.js` with

```javascript
// Compiled by ClojureScript 1.9.908
goog.provide("foo.core");
foo.core.a = (3);

//# sourceURL=foo/core.js?rel=1505912082932
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZm9vL2NvcmUuanM/cmVsPTE1MDU5MTIwODI5MzIiLCJzb3VyY2VzIjpbImNvcmUuY2xqcz9yZWw9MTUwNTkxMjA4MjkzMiJdLCJsaW5lQ291bnQiOjUsIm1hcHBpbmdzIjoiO0FBRUEsYUFBQSxiQUFLQSIsIm5hbWVzIjpbImZvby5jb3JlL2EiXSwic291cmNlc0NvbnRlbnQiOlsiKG5zIGZvby5jb3JlKVxuXG4oZGVmIGEgMylcbiJdfQ==
```

For Lumo, you currently get `.lumo_cache/foo_SLASH_core.js` with

```javascript
goog.provide("foo.core");
(function (){
foo.core.a = (3); return (
new cljs.core.Var(function(){return foo.core.a;},new cljs.core.Symbol("foo.core","a","foo.core/a",(-815575716),null),cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"ns","ns",(441598760)),new cljs.core.Keyword(null,"name","name",(1843675177)),new cljs.core.Keyword(null,"file","file",(-1269645878)),new cljs.core.Keyword(null,"end-column","end-column",(1425389514)),new cljs.core.Keyword(null,"column","column",(2078222095)),new cljs.core.Keyword(null,"line","line",(212345235)),new cljs.core.Keyword(null,"end-line","end-line",(1837326455)),new cljs.core.Keyword(null,"arglists","arglists",(1661989754)),new cljs.core.Keyword(null,"doc","doc",(1913296891)),new cljs.core.Keyword(null,"test","test",(577538877))],[new cljs.core.Symbol(null,"foo.core","foo.core",(-6018953),null),new cljs.core.Symbol(null,"a","a",(-482876059),null),"foo/core.cljs",(7),(1),(3),(3),cljs.core.List.EMPTY,null,(cljs.core.truth_(foo.core.a)?foo.core.a.cljs$lang$test:null)])));})()
;
```

Ignoring, for now, the extra source map information at the bottom of Planck's generated code, for Lumo, you can see that code to return a Var is generated.

Now, when you do something similar with JVM ClojureScript, IIRC, you don't get Vars in the generated JavaScript. So perhaps this entire issue could be characterized as an upstream thing that should be addressed in the self-host code in ClojureScript, with Planck's conditionally omitting `:def-emits-var` for load forms being a workaround for the upstream issue.

**Comment by anmonteiro** [comment]
upstream ticket: https://dev.clojure.org/jira/browse/CLJS-2367

**Comment by mfikes** [comment]
Upstream ticket has been resolved, and, for latest ClojureScript with that fix, Planck is always setting `:def-emits-var` https://github.com/mfikes/planck/commit/a426ff6188b6a5a6c76fda0c7afa562defd76615

**Comment by arichiardi** [comment]
In lumo we do this already https://github.com/anmonteiro/lumo/blob/master/src/cljs/snapshot/lumo/repl.cljs#L1139 so probably the only thing would be to add the logic for `(when-not (neg? (gstring/compareVersions "1.9.933" *clojurescript-version*))`.

But `lumo` ships` with a fixed version of ClojureScript so probably no need for that.

I think we can close this.
