### ISSUE TITLE
Mixed results with andare

### ISSUE THREAD

**Issue by kinleyd** [anmonteiro/lumo#274]
In both Lumo 1.7.0 and 1.8.0 beta, I'm getting different behaviour when using andare 0.7.0.

With these dependencies in the scripts requiring core.async:
(:require [cljs.core.async :as async :refer [>! <! put! chan buffer close! timeout]])
(:require-macros [cljs.core.async.macros :as async-macros :refer [go go-loop]])

Works when calling a script directly these ways:
$ lumo -K -c src:andare-0.7.0.jar wow.cljs
$ lumo -K -D andare:0.7.0 wow.cljs

But fails when using the build.api with the same dependency calls:
$ lumo -c src -c src:andare-0.7.0.jar build.cljs
$ lumo -c src -D andare:0.7.0 build.cljs

In this case I get this error:
Failed! Could not compile cljs.core.async in file cljs/core/async/macros.cljc: Error: Cannot read property 'cljs$core$IFn$_invoke$arity$1' of undefined at line 248 cljs/core/async/macros.cljc
    at new cljs.core.ExceptionInfo (<embedded>:1925:47)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (<embedded>:1928:72)
    at Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$3 (<embedded>:2539:92)
    at Object.cljs.analyzer.macroexpand_1 (<embedded>:3118:329)
    at Function.cljs.analyzer.analyze_seq.cljs$core$IFn$_invoke$arity$4 (<embedded>:3125:35)
    at Object.cljs.analyzer.analyze_form (<embedded>:3162:213)
    at Object.cljs.analyzer.analyze_STAR_ (<embedded>:3165:337)
    at Function.cljs.analyzer.analyze.cljs$core$IFn$_invoke$arity$4 (<embedded>:3170:52)
    at Function.cljs.analyzer.analyze_seq.cljs$core$IFn$_invoke$arity$4 (<embedded>:3125:189)
    at Object.cljs.analyzer.analyze_form (<embedded>:3162:213)

**Comment by mfikes** [comment]
If helpful, here is a link to the macros namespace https://github.com/mfikes/andare/blob/0.7.0/src/main/clojure/cljs/core/async/macros.cljc

**Comment by anmonteiro** [comment]
@kinleyd I can't repro this, it works for me. Can you show me a minimal repro?

**Comment by kinleyd** [comment]
Hi guys, first off: 
@mfikes - thank you for planck and andare!
@anmonteiro - thank you for lumo!
And thank you both for responding so quickly.

Before I try to reproduce the setup, let me try this. I'm getting the feeling that the only difference between my running the script directly and using lumo.build.api lies in my build.settings, which is:

(require '[lumo.build.api :as b])

(b/build "src"
  {:main 'test.core
   :output-to "test.js"
   :optimizations :advanced ;; options: :advanced | :none
   :npm-deps {:pg "7.2.0"} 
   :install-deps true
   :target :nodejs;; ':nodejs' includes shebang for nodejs, which doesn't work inside html
   })

Everything looks fine to me except I'm not sure if there should be settings for clojurescript dependencies similar to :npm-deps? 

I could not find any example of setting clojurescript dependencies in the build script. I only saw examples with it as a part of command line options.

**Comment by anmonteiro** [comment]
I can repro. Seems to be caused with `:optimizations :advanced`.

I'm able to compile with `:optimizations :none`

**Comment by kinleyd** [comment]
Cool. Yes, it runs without error with :optimizations :none.
Good to know that the rest of my build.api settings are OK.

**Comment by anmonteiro** [comment]
This is actually a problem with `:optimize-constants true`

**Comment by anmonteiro** [comment]
upstream JIRA ticket: https://dev.clojure.org/jira/browse/CLJS-2368

**Comment by kinleyd** [comment]
Thanks @anmonteiro, that was most helpful.
