### ISSUE TITLE
Runtime option for disabling --use_strict

### ISSUE THREAD

**Issue by wildermuthn** [anmonteiro/lumo#28]
Some node modules use octal literals, causing errors when node runs in strict mode. Although these node libraries could be patched, it might be useful to include a runtime flag to disable strict mode. Maybe, maybe not. Adding this per Slack request.

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/1cde81a5ffb92438da9e1c321ed0f523be834a0b

Stopped compiling the Lumo binary with a static `--use-strict` option. To note: `--use-strict` is still the default that Lumo ships with, but it is now overridable at runtime with Node's own API:

```clojure
Lumo 1.0.0
ClojureScript 1.9.293
 Exit: Control+D or :cljs/quit or exit
cljs.user=> (js* "066")
SyntaxError: Octal literals are not allowed in strict mode.
cljs.user=> (def v8 (js/require "v8"))
#'cljs.user/v8
cljs.user=> (.setFlagsFromString v8 "--no-use_strict")
nil
cljs.user=> (js* "066")
54
cljs.user=>
```

**Comment by iku000888** [comment]
@anmonteiro 

I know this is a closed topic, but is there a place where these kind of thing get documented?
Seems like a subtle but important feature that deserves more visibility.

Thanks!

**Comment by anmonteiro** [comment]
See #225
