### ISSUE TITLE
lumo.build.api callback should return runable js in callback

### ISSUE THREAD

**Issue by bhurlow** [anmonteiro/lumo#295]
```
lumo -v
Lumo 1.8.0-beta
ClojureScript 1.9.927
Node.js v8.5.0
```

The `1.8.0-beta` build api supports a callback argument which I expected to return compiled js. It appears the tests are aware of this as well. 

I am calling with the following options:

```
(ns lumo.user
  (:require [lumo.build.api]))

(lumo.build.api/build
  "cljs-src"
  {:optimizations :none
   :source-map false}
  (fn [err res]
    (println "ERROR" err)
    (println "RESULT" res)))
```

any reason the build can't return a string there? This would be useful for embedding some build js into a webpage response

**Comment by anmonteiro** [comment]
The callback is going away in the next release. 

The build API is sychronous now.

There's currently no way of returning compiled JS from a call to the build API. Please open a separate issue if you'd like that to be the case (I suspect the most likely to happen would be to print the compiled JS to stdout, I think JVM CLJS does that in some cases).

**Comment by bhurlow** [comment]
ok thanks for clarify
