### ISSUE TITLE
Benchmarks versus raw/native JavaScript?

### ISSUE THREAD

**Issue by taoeffect** [anmonteiro/lumo#297]
I'm sorry if this has been covered somewhere (I searched the issues and didn't find anything).

I'm curious as to how Lumo projects perform versus native JavaScript code?

In other words, does Lumo output a lot of boilerplate that slows down projects significantly? Or is it on par with writing raw JS?

Thanks so much for any help figuring this out!

**Comment by hlolli** [comment]
Calling a cljs function is essentially calling a js function, they perform the same. Clojurescript is immutable and can potentially be faster at some types of code execution than js. The reader is the only thing slower I'd guess, defining functions and macros, aside from complicated macros that are compiled at startup time, this is good as unnoticeable.

**Comment by anmonteiro** [comment]
if you want more general benchmarks you should look for ClojureScript benchmarks. Lumo just makes it easier to write ClojureScript without the JVM. The generated code is the same as the ClojureScript compiler.
