### ISSUE TITLE
Suggestion: highlight repl possibilites

### ISSUE THREAD

**Issue by vemv** [anmonteiro/lumo#303]
Hi!

I'm a quite happy user of JVM-backed cljs with Lein. I go for that since it's what I know, works well, has the most plugins etc.

The only weak spot is when I want a repl NOW for generic stuff. Normally I'd have to

* go to a (properly setup) clojurescript project
* run some command (or even start Emacs)
* wait for JVM startup
* wait for cljs compilation of my whole project

That sucks if all I want is to show `(* 3 2)` to my friend.

So http://clojurescript.io/ is my go-to cljs repl. That's not ideal either - startup could be faster, I don't like the autocompletions / parens matching, etc.

Long story short, I think it'd be be a great value proposition if Lumo offers an instant, project-agnostic repl.

Personally I don't know Lumo much, I suspect it could offer that possibility but it's not highlighted in the README either.

What I'd suggest is:

- make sure lumo offers a repl you can fire up anywhere in less than a second (similar to ruby `irb`).
- make sure getting that comes for default for users, e.g. I `brew install lumo` and already have this instant-generic-repl prepared for me - zero config needed
- Highlight it in the readme!

I'm not asking for this in a whimsical way. I just suggest what could be a killer use case which could skyrocket Lumo's usage.

Cheers - Victor

**Comment by anmonteiro** [comment]
You just described what Lumo does. Is there a question here?

**Comment by vemv** [comment]
I literally didn't know that's what Lumo did. I got the impression that Lumo is more like an alternative way of setting up projects.

Might be worth highlighting this feature in the readme?

**Comment by anmonteiro** [comment]
I thought this was clear from the links in the readme. If you feel like something is lacking, please open a PR!

**Comment by vemv** [comment]
I don't feel comfortable presenting something that is not my creation.

Specifically I'd add:

* the word repl, it's just not there
* highlight why would someone want Lumo (it's fast, it's zero-conf!)
* say something along the lines of "You can install it and run a repl right away"

Btw I just tried out `brew install lumo; lumo` and yeah working as desired! Happy.

Sincerely I hard of Lumo 10-20 times this year and and only today I knew what it could provide.

**Comment by anmonteiro** [comment]
Cool, I'll leave this open until we include something on those lines in the readme
