### ISSUE TITLE
Feature request: Add queue to the repl

### ISSUE THREAD

**Issue by hlolli** [anmonteiro/lumo#307]
In this project here https://github.com/hlolli/lumo-repl-noqueue-benchmark I made a test showing how the lumo process gets very distracted when receiving many callbacks from the repl while performing audio file playback. This is extremely simplified example of lags that I experience when makeing music with lumo where the inf-clojure callbacks for eldoc-completions and arglists are sometimes causing the "musical flow" to hault for sometimes few millisecons, long enough to become noticeable. I'm note sure how best to solve this, a queue or maybe lock sounds plauseable, at least something that ensures that whatever lumo is processing at any given moment does not need to suffer when new data is coming in from the repl. Even tough I used socket repl in this example, I'm assumeing it has more to do with this code here https://github.com/anmonteiro/lumo/blob/571375919a50c06c489435df8014477382675e42/src/js/repl.js#L115, but I couldn't get lumoProcess.stdin.write to work after few attempts.

**Comment by anmonteiro** [comment]
This ticket needs more information, I don't exactly understand what you're requesting

**Comment by hlolli** [comment]
I forgot about this ticket. I was just tripping over the fact that lumo is based in single threaded engine. So when sending code to the repl every 1 millisecond, along with useing the inf-clojure mode in emacs, causes the event loop to stack up, understandably. Much of this was due to inefficiency in inf-clojure which much has been fixed since I opened the ticket. I close it.
