### ISSUE TITLE
Making the classpath dynamic

### ISSUE THREAD

**Issue by nepeckman** [anmonteiro/lumo#31]
Lumo is capable of having dynamic classpath, something that ClojureScript on the JVM cannot do. While not a critical feature, a dynamic classpath opens some interesting options for programs using Lumo.

**Comment by eginez** [comment]
Absolutely I have been thinking about this for a while now, I think resolving dependencies and dynamic classpath can be combined to achieve something like this
(ns org.ns.com 
    :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.229"]
                 [org.clojure/core.async "0.2.391"]])

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/67efbf07047414779db9f5d6ecfd42cb21278dbf
