### ISSUE TITLE
Allow omitting version in -D

### ISSUE THREAD

**Issue by anmonteiro** [anmonteiro/lumo#320]
Same as https://github.com/mfikes/planck/issues/528

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x48b140338183d2086e2eae38cd755ca50186bbfb93d00f0d837f7e771168362f](https://etherscan.io/tx/0x48b140338183d2086e2eae38cd755ca50186bbfb93d00f0d837f7e771168362f)
