### ISSUE TITLE
installation failure using NPM with a GC error.

### ISSUE THREAD

**Issue by paultopia** [anmonteiro/lumo#34]
Hi there, 

Using NPM 3.9.3 on Node 6.2.1 on OSX sierra, lumo failed to install with the following trace: 

```
λ npm install -g lumo-cljs
/Users/pauliglot/.nvm/versions/node/v6.2.1/bin/lumo -> /Users/pauliglot/.nvm/versions/node/v6.2.1/lib/node_modules/lumo-cljs/bin/lumo

> lumo-cljs@1.0.0-alpha3 install /Users/pauliglot/.nvm/versions/node/v6.2.1/lib/node_modules/lumo-cljs
> node scripts/npm_install.js


<--- Last few GCs --->

   43633 ms: Mark-sweep 1374.2 (1435.0) -> 1374.2 (1435.0) MB, 659.6 / 0 ms [allocation failure] [GC in old space requested].
   44427 ms: Mark-sweep 1374.2 (1435.0) -> 1374.2 (1435.0) MB, 711.3 / 0 ms [allocation failure] [GC in old space requested].
   45200 ms: Mark-sweep 1374.2 (1435.0) -> 1374.2 (1435.0) MB, 687.1 / 0 ms [last resort gc].
   46337 ms: Mark-sweep 1374.2 (1435.0) -> 1374.2 (1435.0) MB, 1137.2 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x116a76dc9e59 <JS Object>
    2: fromCharCode(aka fromCharCode) [native string.js:~372] [pc=0x165590d9651a] (this=0x116a76d04101 <null>,an=224)
    3: arguments adaptor frame: 65536->1
    4: string(aka arrayLikeToString) [/Users/pauliglot/.nvm/versions/node/v6.2.1/lib/node_modules/lumo-cljs/node_modules/jszip/lib/utils.js:116] [pc=0x165590d38753] (this=0x1b830f375bd9 <an Object with map 0x171117540381>,array=0x2630781b...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[1]    5140 abort      npm install -g lumo-cljs
```

**Comment by anmonteiro** [comment]
I haven't seen this stack trace before when installing Lumo and it sounds weird to me that it would happen, as the installation script should only be downloading a platform-specific binary.

How much memory does your machine have?

**Comment by paultopia** [comment]
Plenty, it's a fairly well stacked macbook with 16gb ram.  Although I'm using a lot of it right now, I still have 2 or 3 gigs free.  

Hmm... so here's an interesting clue.  I downloaded the binary and stuck it on my path, but when I try to run it, some upstream alias or something is catching the call and throwing the error: 

`/Users/pauliglot/.nvm/versions/node/v6.2.1/bin/lumo: line 1: /lumo.exe: No such file or directory`

... exe?  Did NPM try to install a windows binary on my OSX machine somehow?

**Comment by anmonteiro** [comment]
that's even more strange :) I suggest you delete the following paths and try again:

```
/Users/pauliglot/.nvm/versions/node/v6.2.1/bin/lumo*
/Users/pauliglot/.nvm/versions/node/v6.2.1/lib/node_modules/lumo-cljs
```

**Comment by paultopia** [comment]
that definitely got it working!  odd that it went looking for an .exe file though... I don't see any reason that the build script should be doing that!

**Comment by anmonteiro** [comment]
NPM sets up some shim scripts to be able to run scripts from `cmd.exe` or the Powershell, but that's on windows. I don't know what might be going on.

**Comment by paultopia** [comment]
well, I confirmed that node does realize that `process.platform == 'darwin'` -- and i went poking around the install script and didn't see any obvious causes of this behavior.  So I'm a bit stumped!

**Comment by anmonteiro** [comment]
probably some NPM randomness. I'm going to close this as it doesn't seem at all related to anything in Lumo. Feel free to reopen if you do find some Lumo bug!
