### ISSUE TITLE
How to run ClojureScript Libraries

### ISSUE THREAD

**Issue by Arjuna144** [anmonteiro/lumo#340]
Hi, I really love the project, installed it without problems on windows and it seems to work great.

Now I want to use lumo as a css-preprocessor with the Garden (https://github.com/noprompt/garden)

I could not find documentation or anything about how or if this is possible?

Can you please give some advice and help? 
I would be very happy.

Thanks for the project! :)

**Comment by hlolli** [comment]
This is possible, you probably want to start lumo like this
`lumo -D garden/garden:1.3.3`
if you want garden to spit a css file you'd want to look at fs.readdirSync or use https://github.com/macchiato-framework/macchiato-fs/

I have no example of watcher, but you could for sure make a script that watches your cljs file and compiles css each time you save, this is possible for example with node's fs internal modules.

**Comment by arichiardi** [comment]
Just a not, not all the Cljs libs are self-host compatible.

**Comment by hlolli** [comment]
@arichiardi you are right, garden is sadly one of those libraries that isn't self-host compatible. But as I made Instaparse lumo compatible, then it seemed to always be the same reason, cljc file is calling macro defined in its own file. And in garden we have such a pattern for example here https://github.com/noprompt/garden/blob/master/src/garden/color.cljc#L6

@Arjuna144 your options are either to open a ticket in garden and ask them to make their lib lumo compatable, it's totally possible. Or look at different compilers, I recommend looking at shadow-cljs in that sense.

**Comment by Arjuna144** [comment]
@hlolli Thank you very much for your response! awesome!

**Comment by arichiardi** [comment]
This has been added to the wiki so please refer to it and open another issue if you feel something else should be addressed: https://github.com/anmonteiro/lumo/wiki

Thanks for reporting!
