### ISSUE TITLE
WARNING: cljs.core/bit-or, all arguments must be numbers

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#341]
I have noticed that we have a spurious warning when doing this at the REPL:

```
cljs.user=> (int \uD7ff)
            ⬆
WARNING: cljs.core/bit-or, all arguments must be numbers, got [string number] instead. at line 1 
0
```

It does not happen in vanilla ClojureScript:

```
$ ./script/repljs 
To quit, type: :cljs/quit
cljs.user=> *clojurescript-version*
"1.9.1008"
cljs.user=> (int \uD7ff)
0
```

I will try to dig more, any hint is more than welcome!

**Comment by arichiardi** [comment]
This happens because the line in `target/cljs/tools/reader/edn.js` that triggers the warning is compiled as:

```
cljs.tools.reader.edn.upper_limit = ("\uD7FF | (0));
```

Digging digging...

**Comment by mfikes** [comment]
Being sorted upstream in https://dev.clojure.org/jira/browse/TRDR-50.
