### ISSUE TITLE
Can't cache a namespace with spec defs

### ISSUE THREAD

**Issue by mfikes** [anmonteiro/lumo#359]
Presumably this will occur if Lumo is built against ClojureScript master:

https://github.com/mfikes/planck/issues/647

**Comment by arichiardi** [comment]
Oh the error is the same as in: https://github.com/anmonteiro/lumo/pull/355

Will check that thank you!

**Comment by mfikes** [comment]
If you end up needing to work around the upstream `transit-cljs` issue, one trivial way to do so is to `(clojure.walk/postwalk identity x)` on `x` before passing it to the transit routines. (`walk` will inherently convert any map entries encountered to vectors)

**Comment by arichiardi** [comment]
Thanks I will probably have to!

**Comment by mfikes** [comment]
`transit-cljs` 0.8.248 is available with a fix for the upstream issue

**Comment by arichiardi** [comment]
Thanks Mike, will bump.
