### ISSUE TITLE
Docs not found on compilation targeting :nodejs

### ISSUE THREAD

**Issue by jiyinyiyong** [anmonteiro/lumo#389]
I got two files `src/app/main.cljs`:

```clojure
(println "Hello world!")
```
and `build.cljs`:

```
(require 'lumo.build.api)

(lumo.build.api/build "src" {:output-to "out/main.js"
                             :target :nodejs})
```

and I want to compile it and run in Node.js , but it doesn't work as expected. Docs required.

**Comment by jiyinyiyong** [comment]
I expected I could get a `out/main.js` file which I can run with `node out/main.js` to call `println`... but it didn't as I described on Slack. The simplest example should work out of box, otherwise people get confusions.

**Comment by arichiardi** [comment]
@jiyinyiyong I think you cannot compile with `:main`, in vanilla ClojureScript should be the same:

```
$ clojure -A:cljs-canary -m cljs.main -t nodejs -c
Exception in thread "main" java.lang.AssertionError: Assert failed: :nodejs target with :none optimizations requires a :main entry
(not (and (= target :nodejs) (= optimizations :none) (not (contains? opts :main))))
	at cljs.closure$check_node_target.invokeStatic(closure.clj:2107)
        ...
```

Probably this issue should be renamed in order to see why we don't throw.

**Comment by arichiardi** [comment]
Will try to put an example together as soon as I have some more time. Note that the compilation is not yet documented well because of the super-alpha status :smile: Will improve over time.

**Comment by anmonteiro** [comment]
This now fails with `Assert failed: :nodejs target with :none optimizations requires a :main entry` after we upgraded the ClojureScript version.

**Comment by arichiardi** [comment]
Haven't had time yet for the example, however the wiki is a good place to contribute one if somebody has one ready ;)
