### ISSUE TITLE
Consider making lumo.repl/st public

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#405]
One of the biggest advantage of `lumo` over  JVM for tooling is direct access to the compiler state.

At the moment we have:

```clojure
(defonce ^:private st (cljs/empty-state))
```

Something like `cljs-tooling` might actually want to access to it [directly](https://github.com/clojure-emacs/cljs-tooling/blob/master/src/cljs_tooling/complete.clj#L35-L39) so I think it makes sense to make it public at some point.

Thoughts?

**Comment by anmonteiro** [comment]
shouldn't it be accessible with `cljs.env/*compiler*`?

**Comment by arichiardi** [comment]
You are right (of course), it is!

```
Lumo 1.9.0-alpha
ClojureScript 1.10.238
Node.js v8.10.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (require '[cljs.env :as env])
nil
cljs.user=> (def state @env/*compiler*)
#'cljs.user/state
cljs.user=> (take 10 (keys (get-in state [:cljs.analyzer/namespaces 'cljs.core :defs])))
(->PersistentHashSet
 js->clj
 sort-by
 ITransientAssociative
 chunk-first
 print-meta?
 m3-hash-int
 pr-str*
 eduction
 tree-seq)
```
