### ISSUE TITLE
package.json is missing `opencollective` as a dependency.

### ISSUE THREAD

**Issue by johanatan** [anmonteiro/lumo#409]
title says it all.

**Comment by anmonteiro** [comment]
`opencollective` shouldn't be a dependency of the installed Lumo binary.

What is this issue about? can you provide more context?

**Comment by anmonteiro** [comment]
FWIW it's a `devDependency` in the top-level `package.json`:
https://github.com/anmonteiro/lumo/blob/master/package.json#L55

This is, however, a "private" `package.json` that is not part of the published NPM package.

**Comment by johanatan** [comment]
Post-install script fails during install of `lumo-cljs` via `npm install -g lumo-cljs` in the ubuntu codebuild environment on AWS.

[This also happens when installing `closh` which is based on `lumo`].

**Comment by anmonteiro** [comment]
@johanatan there's no postinstall script (https://github.com/anmonteiro/lumo/blob/master/packages/lumo/package.json) in the published Lumo package.

**Comment by anmonteiro** [comment]
Please note that trying to install Lumo from master doesn't really work (i.e. `npm install github:anmonteiro/lumo` or somesuch)

**Comment by johanatan** [comment]
Oh, sorry. This is when installing `1.9.0-alpha` from a git tag:

`npm install anmonteiro/lumo#1.9.0-alpha` for example.

**Comment by johanatan** [comment]
[And I'm trying to install 1.9.0-alpha because of the corrupted zip problem].

**Comment by anmonteiro** [comment]
Yeah that doesn't work. I'll go ahead and publish 1.9.0-alpha on NPM which I didn't yet.

**Comment by johanatan** [comment]
Ok, in this case, can you please release the corrupted zip fix to npm?

**Comment by johanatan** [comment]
Thank you.

**Comment by anmonteiro** [comment]
Done! Closing.
