### ISSUE TITLE
Getting started - how to output JavaScript

### ISSUE THREAD

**Issue by slifin** [anmonteiro/lumo#422]
I've written hello world in my cljs file and can run it with ```lumo hello_world.cljs``` 

Is there an inbuilt way of outputting the JavaScript created from Clojure?

**Comment by slifin** [comment]
ok this is what I learnt to get hello world running on lumo, (expect errors in the explanation)

First, you need a build script, I found mine from here: https://anmonteiro.com/2017/02/compiling-clojurescript-projects-without-the-jvm/

```
(require '[lumo.build.api :as b])

(b/build "src"
  {:main 'hello_world.core
   :output-to "main.js"
   :optimizations :advanced
   :target :nodejs})             
```    

the filename is ```build.cljs```

I can make a guess on what most of it does but I don't where to go for documentation on this build, I suspect here: https://github.com/anmonteiro/lumo/blob/master/src/cljs/bundled/lumo/build/api.cljs but since I don't read fluent Clojure that could be an issue, either way forget about that for now 

The :main key appears to point to a namespace, I think the convention of this language is for each part in the namespace you need a folder, with a file at the end, so hello_world.core means you need a folder called hello_world with a file called ```core.cljs``` but I think this needs to all exist in the folder defined in the first parameter of b/build, so in this case "src"

So create a folder structure + file in your current dir of:

src/hello_world/core.cljs

then inside there we need the namespace:

``` (ns hello-world.core)```

then I tried to do:

```
(println "Hello World!")
```
but after compiling that later I got an error, so this is required:
```
(enable-console-print!)
```

completed core.cljs:

```
(ns hello-world.core)
(enable-console-print!)
(println "Hello World!")
```

Once you have those pieces you can run the following:

```lumo -c src build.cljs ```

in your project root, after a while you'll get a main.js in that directory which you can run with node:

```
~/C/lumo node main.js 
Hello World!
```

Horray 🎉 

I've also seen you can just do ```(println "Hello World!")``` inside hello.cljs then do ```lumo hello.cljs``` if you're not worried about a JavaScript output

**Comment by anmonteiro** [comment]
Looks like this is no longer an issue? feel free to reopen
