### ISSUE TITLE
Use Buffer.alloc instead of Buffer

### ISSUE THREAD

**Issue by hlolli** [anmonteiro/lumo#425]
Just post it here so I won't forget it, I compiled lumo with node 10.7.0, and with node 10x `new Buffer()` has beed deprecated, as described with this warning when running lumo compiled against this pre-mentioned node version

```
 (node:8283) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

My bet is on this line https://github.com/anmonteiro/lumo/blob/2b4bc09f768fc57164cebc99a90b95bdb1a26762/scripts/embed.js#L7

Will test it and make PR when I have time.

**Comment by anmonteiro** [comment]
We have a fix for this in https://github.com/anmonteiro/lumo/pull/387
