### ISSUE TITLE
Live reload recommendation

### ISSUE THREAD

**Issue by Immortalin** [anmonteiro/lumo#426]
What's the recommended way of live-reloading server-side code on save?

**Comment by jiyinyiyong** [comment]
If you don't insist in Lumo, you may try https://github.com/minimal-xyz/minimal-shadow-cljs-nodejs . 

fighwheel-main might be also a nice option if you know Java/Clojure well.

**Comment by hlolli** [comment]
If you mean server-side as in node-express (not clj) then
```
(require 'lumo.build.api)

(lumo.build.api/watch
         "samples/hello"
         {:optimizations :none
         :output-to "samples/out/hello.js"
         :output-dir "samples/out"
         :cache-analysis true
         :source-map true
         :verbose true
         :watch-fn
         (fn []
             (println "Success!"))})
```

**Comment by hlolli** [comment]
This was just a copy/paste above, you'd want to configure for node.js output. The `lumo.build.api/build` and `lumo.build.api/watch` both follow https://clojurescript.org/reference/compiler-options

**Comment by Immortalin** [comment]
Thanks!
