### ISSUE TITLE
Browser only target

### ISSUE THREAD

**Issue by Immortalin** [anmonteiro/lumo#427]
Is it possible to add a target that is browser-only i.e. full google closure compiler but no dependency on node?

**Comment by arichiardi** [comment]
Hi!

Not sure this is doable. Lumo needs to run somehow the compiler and whereas the classic ClojureScript runs on the JVM, Lumo runs on node.

Adtidionally, there is no dependency carried over after JavaScript gets compiled. Please note that compilation is still rough. The browser target should be working though.

Did I understand the question correctly?

**Comment by Immortalin** [comment]
What I mean is to compile Lumo to run fully client-side in-browser.

**Comment by arichiardi** [comment]
Oh ok for a REPL? There is https://github.com/arichiardi/replumb but it is quite outdated at the moment. I am still working on bringing it up to speed :smile:

**Comment by Immortalin** [comment]
I don't mean just the plain bootstrapped Clojure. I mean the whole Google Closure Compiler too. Chrome and Node use the same V8 engine. The only difference is how io/operating systems/a few environment variables are handled. Is it possible to run Lumo instead of clj.js for client side?

**Comment by Immortalin** [comment]
Replumb looks amazing btw :D

**Comment by arichiardi** [comment]
At the moment nobody has attempted that, what would be the use case? Curious what you have in mind...full compile in the browser is a bit obscure to me :smile:

GCC JS could definitely run in a browser if you replace all the IO functions correctly but it would be super slow I guess?

**Comment by Immortalin** [comment]
Wait..hang on if I understand this correctly, ClojureScript strictly doesn't NEED the Closure compiler right? It works fine by itself the closure compiler is just an optimization pass am I right?

**Comment by Immortalin** [comment]
According to Closure README it can be ran in-browser :D
