### ISSUE TITLE
GitHub reports security issues using lumo

### ISSUE THREAD

**Issue by nfuhs** [anmonteiro/lumo#428]
Hi,
I just a heads up  if I use latest lumo in my [app-boilerplate](https://github.com/nfuhs/lumo-starter) and push to GitHub,  GitHub reports security issues:

Known  high severity security vulnerability detected in cryptiles < 4.1.2 defined in package-lock.json.
--
package-lock.json update suggested: cryptiles ~> 4.1.2

and

Known  moderate severity security vulnerability detected in hoek < 4.2.1 defined in package-lock.json.
--
package-lock.json update suggested: hoek ~> 4.2.1.

**Comment by anmonteiro** [comment]
I don't think this is true. GitHub is probably analyzing the `package.json` at the root of this repo, but the installed version is actually in `packages/lumo/package.json` which I don't think includes those dependencies. 

In any case I bumped the deps in https://github.com/anmonteiro/lumo/pull/429
