### ISSUE TITLE
lumo-1.9.0 tries to download a broken link to har-validator.

### ISSUE THREAD

**Issue by crocket** [anmonteiro/lumo#455]
```
Installing node dependencies with `yarn install`
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpe
cted end of data"
```

**Comment by daviwil** [comment]
Hey @crocket, I've fixed this issue by updating `yarn.lock` to use a newer patch version of `har-validator`.  It's on a branch of my fork if you'd like to give it a try to get unblocked: https://github.com/anmonteiro/lumo/pull/456

**Comment by rpodgorny** [comment]
please take a look at this, it blocks me also... :-(
