### ISSUE TITLE
installation: "This method has been removed in JSZip 3.0"

### ISSUE THREAD

**Issue by mars0i** [anmonteiro/lumo#46]
Hi, I found that I had to install these npm modules for lumo:
jszip
set-immediate

After doing that, I still get this error with npm 3.10.9 and node v7.2.0:

```
sudo npm install -g lumo-cljs
/usr/local/bin/lumo -> /usr/local/lib/node_modules/lumo-cljs/bin/lumo

> lumo-cljs@1.0.0 install /usr/local/lib/node_modules/lumo-cljs
> node scripts/npm_install.js

/usr/local/lib/node_modules/jszip/lib/object.js:170
        throw new Error("This method has been removed in JSZip 3.0, please check the upgrade guide.");
        ^

Error: This method has been removed in JSZip 3.0, please check the upgrade guide.
    at JSZip.load (/usr/local/lib/node_modules/jszip/lib/object.js:170:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/lumo-cljs/scripts/npm_install.js:40:34)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "lumo-cljs"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! lumo-cljs@1.0.0 install: `node scripts/npm_install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lumo-cljs@1.0.0 install script 'node scripts/npm_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lumo-cljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/npm_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lumo-cljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lumo-cljs
npm ERR! There is likely additional logging output above.
```

I can insert the npm-debug.log file, too, if that's helpful.

I'm not a regular node or npm user, and have had wierd difficulties with npm in the past as well.  I'm sure they're great once you get them working, but npm has only caused  headaches for me.  Sigh. If you find this problem mysterious, and if I'm the only person who reports it, it's OK to ignore it.  I have planck working, which seems quite fast enough, so I can live without trying lumo if need be.    Thanks.

**Comment by leppert** [comment]
@mars0i in the meantime, you can install via [Homebrew](http://brew.sh) using `brew install lumo`

**Comment by mars0i** [comment]
Oh, noo ... now I have to install Homebrew, too. OK.  Thanks.  Will try that.

**Comment by anmonteiro** [comment]
It doesn't make sense to me why you'd have to install JSZip. the `lumo-cljs` package describes a clear dependency that should be installed as part of the process. In any case, it requires JSZip `2.6.1`, which is why you're getting errors with the latest version.

**Comment by mars0i** [comment]
Thanks anmonteiro.  As a node/npm outsider, I'm coming to dislike npm a lot.  No doubt because I don't understand it.  It's a package manager, but it hasn't done much to manage packages for me.  Getting it to install something I want is like trying to compile an old C program written for a different operating system.  (error, fix, error, fix, install lib, error, fix, remove a different lib, error, change lib path, fix, error, fix etc. :-)    I'm not going to ask you to teach me the ins and outs of npm in a github issue, though.

**Comment by anmonteiro** [comment]
I can't say I have the best regard for NPM too, especially being used to Maven. But this is not the place to discuss that anyway, and there are alternatives like Yarn which you can maybe try out.

I am, however, interested to know if you managed to install Lumo via NPM in the end.

**Comment by mars0i** [comment]
Just got it working!  I got the right version of jszip installed, and then the lumo-cljs install also needed pako.  Once that was installed, lumo-cljs got installed.  Thanks.

**Comment by anmonteiro** [comment]
awesome, glad to hear. I'm closing this then. Let me know if you run into any other issues.

**Comment by mars0i** [comment]
Thanks--will do.  I wonder if it would be helpful to add to README.md commands to install jszip 2.6.1, set-immediate, and pako.  It seems likely that others might encounter the same problems.  I can edit README.md and issue a pull request if that's OK.

**Comment by anmonteiro** [comment]
I'm not sure that's actually a problem, NPM should install a package's dependency's when requested to install such package. I need to hear reports from more people before taking any action.

**Comment by mars0i** [comment]
Understood.  Thanks.
