### ISSUE TITLE
*command-line-args* doesn't work in node

### ISSUE THREAD

**Issue by benjamincassidy** [anmonteiro/lumo#461]
I've got this code

```
(ns core
  (:require [cljs.core :refer [*command-line-args*]]))

(enable-console-print!)

(println "Hello World!" *command-line-args*)
```

When I run
```
lumo core.cljs test argument
```
it prints
```
Hello World! (test argument)
```

After compiling to node and running
```
./main.js test argument
```
The output is
```
Hello World! nil
```

Is this expected behavior, a bug, or a user error?

**Comment by anmonteiro** [comment]
Albeit a bit unexpected, this is user error. `*command-line-args*` is functionally equivalent to `clojure.main`'s:

> Binds *command-line-args* to a seq of strings containing command line args that appear after any main option

[source](https://clojure.org/reference/repl_and_main#_clojure_main_help)

So in your case the "main option" is `core.cljs` when you call it with `lumo core.cljs test argument`.

If you're gonna compile to JavaScript (and run on Node) I would suggest using `js/process.argv` or whatever the equivalent might be for ClojureScript on Node.js (I'm fuzzy on the details).
