### ISSUE TITLE
Spurious toine in lumo banner

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#484]
Hi Antonio!

I have noticed this in the latest `master`:

```
toine [ '/home/arichiardi/bin/lumo' ]
Lumo 1.10.1
ClojureScript 1.10.520
Node.js v12.0.0

...
```

It seems to come from `exe.js` and I can of course easily get rid of it:

```
if (!process.send) {
  console.log('toine', global.process.argv);
  process.argv.splice(1, 0, 'nexe.js');
}
```

Just wanted check with you first if it is a leftover or necessary.

Thanks a lot as usual for your work on Lumo! :smile: 

P.S.: this one is the statically compiled version against `musl`, does it make any difference?

**Comment by anmonteiro** [comment]
fixed in #479
