### ISSUE TITLE
Different startup times for -e vs. stdin

### ISSUE THREAD

**Issue by cellularmitosis** [anmonteiro/lumo#496]
Hello,

Just something odd which I ran across and was curious about.  The typical way I benchmark the startup time of a lisp is to pipe `(+ 1 1)` into its standard input.  It turns out this is significantly slower than using `-e` for lumo:

```
cell@opti:~$ time echo '(+ 1 1)' | lumo
Lumo 1.10.1
ClojureScript 1.10.520
Node.js v11.13.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (+ 1 1)
2
cljs.user=> 
real	0m0.595s
user	0m0.934s
sys	0m0.057s
```

```
cell@opti:~$ time lumo -e '(+ 1 1)'
2

real	0m0.206s
user	0m0.255s
sys	0m0.017s
```

Just curious if you knew where the disparity comes from, thanks again for working on lumo!  

Edit: for reference, this is on a quad-code i5:

```
cell@opti:~$ cat /proc/cpuinfo | grep 'model name'
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
```

**Comment by penryu** [comment]
I can't say for certain, but I wonder if the answer lies in the presence of the banner when piping to stdin:

```
Lumo 1.10.1
ClojureScript 1.10.520
Node.js v11.13.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=>
```

I suspect passing `-e` tells the process it has only to evaluate the argument(s).

In the absence of `-e`, lumo spins up an entire interactive REPL, drawing input from stdin if open.

**Comment by cellularmitosis** [comment]
Thanks!
