### ISSUE TITLE
jszip no longer available

### ISSUE THREAD

**Issue by Mic92** [anmonteiro/lumo#500]
cc @hlolli 

```
$ npm update
npm WARN deprecated rollup-plugin-babel-minify@9.1.1: Please use rollup-plugin-terser instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated rollup-plugin-replace@2.2.0: This module has moved and is now available at @rollup/plugin-replace. Please update your dependencies. This version is no longer maintained.
npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm ERR! Error while executing:
npm ERR! /run/current-system/sw/bin/git ls-remote -h -t ssh://git@github.com/anmonteiro/jszip.git
npm ERR!
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joerg/.npm/_logs/2020-05-04T11_36_00_555Z-debug.log
```

**Comment by hlolli** [comment]
@Mic92 thanks for the report!

The author of lumo has abandon the project, but left me and few others with access. So I'll try to fix this soon!

**Comment by Mic92** [comment]
This is currently blocking re-building node-packages in nixpkgs. So we need a result soonish or we need to mark lumo as broken in nixpkgs.

**Comment by hlolli** [comment]
I'll find a solution in this PR
https://github.com/NixOS/nixpkgs/pull/80655/files
it's been there open for some time now

**Comment by Mic92** [comment]
This PR does not fix it on master though.

**Comment by hlolli** [comment]
Sorry I'll ping you when it's fixed. Just pointing out that I'll fix it there instead of new PR.

**Comment by Mic92** [comment]
ok.

**Comment by hlolli** [comment]
PR updated on nixpks https://github.com/NixOS/nixpkgs/pull/80655

it's bit messy, just tell me if you need some cleanup.

For the solution itself, it should be solid for now.

Also anyone reading this, since the darwin changes got merged, it seems to be failing https://nix-cache.s3.amazonaws.com/log/34g6r965la8006aikyrajckjdc6p9hn2-node_lumo-build-deps-1.10.1.drv due to xcodebuild not being in scope for a npm dependency.

I'll fix this later (then again, Darwin seems to be hard to get right).
