### ISSUE TITLE
child_process.fork() causes repl to be run in subprocess

### ISSUE THREAD

**Issue by jjl** [anmonteiro/lumo#53]
Pleasingly, clojurescript "just works" in the child process, along with the repl. Sadly this means two things:
a) the banner and prompt are printed again when a child process is forked
b) keyboard input is processed by both processes

Not sure what the solution is here, I've not spent too much time in the nodejs ecosystem.

Repro cljs:

```cljs
(def child-process (js/require "child_process"))
(.fork child-process "noop.js")
```

noop.js:

```javascript
"use strict";
module.exports = function () {};
```

**Comment by anmonteiro** [comment]
can't repro here. Instead I get an infinite printing loop of `Illegal option -- --child_process`.

**Comment by jjl** [comment]
Having updated to the latest master, I now get what you get.

Also a bug, but a slightly different one. And no clue why.

**Comment by jjl** [comment]
It gets weirder - when i run `npm run-script dev`, it works just fine. Only the built lumo fails.

**Comment by anmonteiro** [comment]
I think I know what is going on. You may want to `child_process.exec` instead of `fork`, because of the startup snapshots

**Comment by jjl** [comment]
Is there a command line option for loading a custom snapshot into node that I can use with a plain cljs snapshot? How would I go about making a snapshot like that?

**Comment by anmonteiro** [comment]
FWIW this is a limitation of Nexe, as per their [README](https://github.com/nexe/nexe#child_processfork)
