### ISSUE TITLE
Use leiningen dependencies

### ISSUE THREAD

**Issue by turbopape** [anmonteiro/lumo#6]
Hey, nice work !
It would be nice if lumo could detect the presence of then parse project.clj (if present) and guess dependencies, then automatically add those if present in ~/.m2/repository... ( so we dont waste time loading them evereytime)

This way we can run a project -aware repl :)

**Comment by anmonteiro** [comment]
You should be able to do what you want via
```
lumo -c `lein classpath`
```

**Comment by gniquil** [comment]
This might be a stupid question, but, core async doens't work right? I added core.async to the project.clj file have the source script:
```clorejure
(ns simple-script
  (:require-macros [cljs.core.async.macros :refer [go go-loop]])
  (:require [cljs.core.async :refer [put! chan <! >! timeout close!]]))
```
and ran lumo like you had above with `-c`, but got error like this:
```
#error {:message No such namespace: java.util.concurrent.locks.Lock, could not locate java/util/concurrent/locks/Lock.cljs, java/util/concurrent/locks/Lock.cljc, or Closure namespace "java.util.concurrent.locks.Lock" in file cljs/core/async/impl/ioc_macros.clj, :data {:tag :cljs/analysis-error}}
```

**Comment by anmonteiro** [comment]
That's right. Mike Fikes has a port of core.async that works in bootstrapped ClojureScript: https://github.com/mfikes/andare

**Comment by turbopape** [comment]
Thanks for the hint !

**Comment by turbopape** [comment]
I am having problems with libs that don't know how to talk with bootstrapped cljs as well... maybe another reader conditional alternative  #?(:cljb ... ?  :)

**Comment by turbopape** [comment]
Once again I discover that cljs is too tighed into java world ( as a Clojure program)...

**Comment by anmonteiro** [comment]
I'm not sure what you want Lumo to solve here anymore. If you want to use certain libraries in Lumo they must be compatible with self-hosted ClojureScript. There's just no way around that.

**Comment by turbopape** [comment]
yes you're right :) I didn't blame anything on Lumo, it's just some old concerns about cljs in general, sorry to have posted them here, definitely not their place :)
Kudos for the great work ! 👍

**Comment by gniquil** [comment]
Hi @anmonteiro, 

Have you ever talked to @mfikes about unifying some type of interface/standards for all bootstraped runtimes? For example, cljs lacks `slurp`. Planck has an implementation, in Lumo we can do the same with `readFile[Sync]`. But the problem for library authors then would be write a different version of code for each environment. This could be painful, and made worse that we also have the browser and jvm runtime. It would be nice for all runtimes to formulate some type of standards so libraries can be easier to write, and applications perhaps more portable. `cljc` could be one way to approach, but feels non-scalable (i.e. for each runtime we will have a :clj(?)). Hopefully you guys can come up something great.

Nevertheless, I'm so excited about this. (Did Lumo just kill pixie? :))

**Comment by anmonteiro** [comment]
I have talked with Mike briefly about setting something like that up. Hopefully we'll be able to create some common interface based on protocols that different runtimes can implement :)

**Comment by arichiardi** [comment]
@gniquil Not about I/O specifically, but there is common plumbing for all `cljs` bootstrapped repls already, which is what [klipse](https://github.com/viebel/klipse) uses as well. It is [replumb](https://github.com/Lambda-X/replumb).

I tried to separate in there between different runtimes (for now just `:browser` and :nodejs`) and [indeed](https://github.com/Lambda-X/replumb/tree/master/repl-demo) the approach is doable.
Also, `replumb.browser.io` and `replumb.nodejs.io` are already [there](https://github.com/Lambda-X/replumb/tree/master/src) (maybe the naming can be unified).

I never had the need myself to extend this as I am using the two namespaces only for testing and demos, but of course PRs/new ideas are more than welcome!

**Comment by gniquil** [comment]
@arichiardi Thanks for pointing out. This is great. (A side question, why all the "Sync" versions for io? Those functions accept callbacks already. Or put it different, what's point of having callbacks if it's "Sync")

**Comment by arichiardi** [comment]
Good question, probably at the time I needed control over the return values to my callback and I was noticing issues with the async versions. Some work definitely needs to be done in there, I just wanted to show that `replumb` can be used for that ;)

**Comment by jmfirth** [comment]
Hello @anmonteiro.  Love the work you're doing here.  Was interested in OP's answer but on a Windows environment.  Obviously something like this wont work there: 

```sh
lumo -c `lein classpath`
```

Below is a rough approximation for Windows that I was not able to get working properly:

```
lein classpath > classpath
set /P LEIN_CLASSPATH =<classpath
lumo -c %LEIN_CLASSPATH%
```

Any ideas?

**Comment by anmonteiro** [comment]
I'm closing this. Feel free to reopen if it's still an issue.

**Comment by JimTheMan** [comment]
Hi, sorry to reopen a zombie issue, but "lein -c project.clj" doesn't do anything for me. It just loads a default prompt with cljs.user and no namespaces loaded in. How can I just have all of my files and all dependencies downloaded and loaded into lumo?

**Comment by sheunaluko** [comment]
Hi JimTheMan, I am just a passerby here but I do notice at the top of this thread ammonteiro has stated : 

You should be able to do what you want via
lumo -c `lein classpath`

--- 

This was in response to
It would be nice if lumo could detect the presence of then parse project.clj (if present) and guess dependencies, then automatically add those if present in ~/.m2/repository... ( so we dont waste time loading them evereytime)

This way we can run a project -aware repl :) 

--- 

Sorry if this is not what you meant but thought id say something
