### ISSUE TITLE
Search history with buffer on pressing arrow key

### ISSUE THREAD

**Issue by jiyinyiyong** [anmonteiro/lumo#62]
It's a feature in Boot REPL. I don't know what to call it but I use it for long. For example I got some histories:

```clojure
(+ 1 2)
(+ 2 3)
(- 2 1)
(- 3 2)
```

Now I typed `(+` in the REPL and use `Up` key to find history. Currently I got any history one by one. But in Boot, only `(+ 1 2)` `(+ 2 3)` are matched since the beginner characters are the same.

I'm considering it as a new feature we need.

**Comment by arichiardi** [comment]
Wow neat, you made me discover this feature in boot repl 😁

**Comment by anmonteiro** [comment]
If we're going to do something similar, I would probably prefer implementing something like Planck's new [reverse i-search](http://blog.fikesfarm.com/posts/2017-02-11-apt-get-install-planck.html) feature. 

@jiyinyiyong Thoughts?

**Comment by jiyinyiyong** [comment]
Well, I think `history-search-backward` is easier to implement since we only need to test with `start-with?`. **reverse i-search** would be fine. But I have to say personally I never used `Ctrl R` in real my work.

**Comment by didibus** [comment]
I think I prefer reverse-i-search since it's more standart across shells, more people will know about it instinctively. It's also more  powerful. 

I can also find the up behavior a bit intrusive. Reber i search is more optional.

**Comment by anmonteiro** [comment]
PR in #169

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/8486b14b8aeafc1482e97dc5cc4ad3267e25dafb
