### ISSUE TITLE
Rejected promises can't be catched

### ISSUE THREAD

**Issue by honzabrecka** [anmonteiro/lumo#63]
The problem is that `catch` method is due to some reason (catch is reserved word in javascript) renamed to `catch$`, which is obviously not available on returned promise:

```clj
(let [Promise (js/require "bluebird")]
  (.catch (Promise. #(%2 "x")) #(println %)))
```

```
(function (){var Promise = require("bluebird");
return (new Promise(((function (Promise){
return (function (p1__47_SHARP_,p2__46_SHARP_){
return p2__46_SHARP_.call(null,"x");
});})(Promise))
)).catch$(((function (Promise){
return (function (p1__48_SHARP_){
return cljs.core.println.call(null,p1__48_SHARP_);
});})(Promise))
);
})()
TypeError: (intermediate value).catch$ is not a function
```

**Comment by anmonteiro** [comment]
[CLJS-1831](http://dev.clojure.org/jira/browse/CLJS-1831) has been solved in ClojureScript master. I'll test this out in Lumo to see if your repro now works.

**Comment by anmonteiro** [comment]
This has been captured in [CLJS-1949](http://dev.clojure.org/jira/browse/CLJS-1949).

**Comment by anmonteiro** [comment]
This has been fixed upstream (https://github.com/clojure/clojurescript/commit/025dd9d3e57f1955fd442b9f69823c892a38cb58) and will be in the next version of Lumo.
