### ISSUE TITLE
Preamble should be removed when running in a script

### ISSUE THREAD

**Issue by ohpauleez** [anmonteiro/lumo#65]
First and foremost, thanks for the work on pulling lumo together!  Great work!

When scripting with lumo via a shebang'd file, lumo prints the preamble message from the repl initialization.  This is problematic if you're piping commands together or otherwise redirecting the output.

For example, given the executable file `test.cljs`

``` clojure
#!/usr/bin/env lumo

(println "Hello World")
```

... will result in:

```
$ ./test.cljs
Lumo 1.0.0
ClojureScript 1.9.293
 Docs: (doc function-name-here)
 Exit: Control+D or :cljs/quit or exit

Hello World!
```

**Comment by anmonteiro** [comment]
Thanks for bringing this up. It has, however, been fixed in master as of https://github.com/anmonteiro/lumo/commit/e144add5d860224cbd24ac84c8d7932a8e6dad69.

You can download a built executable from a passing commit from the CI. Which OS are you running?

**Comment by ohpauleez** [comment]
Awesome, thanks!

(I thought it was fixed on master, but wanted to open the issue to document it, so it'd be picked up on Google :) )

**Comment by anmonteiro** [comment]
Expanding on the hint I gave earlier, you can download Lumo artifacts from master commits in the respective CIs:

- [OSX artifact example](https://circleci.com/gh/anmonteiro/lumo/227#artifacts/containers/0)
- [Windows artifact example](https://ci.appveyor.com/project/anmonteiro/lumo/build/212/artifacts)
- For Linux, we currently only store the latest successful build, which you can access through [this link](https://s3.amazonaws.com/lumo-linux/lumo)

**Comment by jiyinyiyong** [comment]
Some note here. The OSX artifacts can only be seen after logged in...
