### ISSUE TITLE
on CLI arguments

### ISSUE THREAD

**Issue by jiyinyiyong** [anmonteiro/lumo#68]
I was trying commands like:

```bash
lumo -i args.cljs p1 p2
```

and to read them:

```cljs
(println js/process.argv)
```

But Lumo turned out to see them as filenames. Is that by design or just a bug?

```bash
#js [/usr/local/Cellar/lumo/1.0.0/bin/lumo nexe.js -i args.cljs p1 p2]
#error {:message Could not load file p1, :data {}}
```

**Comment by anmonteiro** [comment]
This is by design. We try to copy Clojure where possible. example: 

```clojure
;; foo.clj
(println (+ 1 2))
```

```sh
$ java -jar clojure.jar -i foo.clj foo.clj
3
3
```

**Comment by anmonteiro** [comment]
I should clarify. In your example, only `p1` is treated as a file. `p2` will be put under `*command-line-args*`

**Comment by jiyinyiyong** [comment]
Sounds alien seeing from JavaScript site 😆
