### ISSUE TITLE
Http requests without dependencies?

### ISSUE THREAD

**Issue by pe3** [anmonteiro/lumo#70]
How would it be possible to get data from a REST-API without dependencies? I'm new to ClojureScript but using Lumo for simple network scripting seems tempting to me. I just wouldn't want to start importing dependencies next to my script. 

Sorry this must be a stupid question. I just couldn't resist asking it. And maybe it is something other people coming from Node would be interested in. I'm hoping to learn ClojureScript basics through scripting to be able to work on web projects later on.

**Comment by jiyinyiyong** [comment]
I guess:

```cljs
(def http (js/require "http"))

(def app (.createServer http (fn [req res] (.end res "ok"))))

(.listen app 3000)

(def options (clj->js {:host "localhost", :port 3000, :path "/"}))

(.get http options
  (fn [response]
    (let [body-ref (atom "")]
      (.on response "data" (fn [chunk] (swap! body-ref str chunk)))
      (.on response "end" (fn [] (println @body-ref))))))
```

**Comment by anmonteiro** [comment]
@jiyinyiyong's answer should be the way to go. Lumo has access to all the Node.js packages so you can even use [Request](https://www.npmjs.com/package/request) if you feel like.

A `lumo.http` namespace may appear in the future, but for now you have to resort to Node.js interop.

I'm closing this now. Feel free to reopen if it is still an issue.

**Comment by pe3** [comment]
Thanks! Couldn't figure out those callback-functions myself.

**Comment by jiyinyiyong** [comment]
try this http://www.spacjer.com/blog/2014/09/12/clojurescript-javascript-interop/
