### ISSUE TITLE
Cache not working?

### ISSUE THREAD

**Issue by borkdude** [anmonteiro/lumo#73]
I have script in `script.cljs`: 

https://github.com/borkdude/rafflers/tree/master/borkdude-cljs-node-lumo

I execute this script like this:

    ./node_modules/lumo-cljs/bin/lumo -K script.cljs /tmp/names/current

The last argument can be any text file containing some lines. It will return a random line from the text file. It may also be omitted. 

I expect the `.lumo_cache` to contain something after the initial run, but this directory stays empty.

**Comment by jiyinyiyong** [comment]
I guess Lumo only caches files from libraries according to my experience, which are specified in `classpath`

**Comment by anmonteiro** [comment]
We can definitely cache the file you're executing, and there seems to be a Lumo bug there, but if the namespace and the path don't match (as in your example), it serves little purpose, as evaluation won't be able to find the cached source.

**Comment by borkdude** [comment]
@anmonteiro I'll change the namespace to `script`. Thanks!

**Comment by anmonteiro** [comment]
That will probably work, but note this still doesn't work. It's an easy fix, though, and should make it to the next release

**Comment by borkdude** [comment]
@anmonteiro No worries, I'm not in a hurry.

**Comment by anmonteiro** [comment]
fixed https://github.com/anmonteiro/lumo/commit/f91d1651ac5de36ddd262e43305e5eab3c6b5b52
