### ISSUE TITLE
(require <ns> :reload) doesn't invalidate the cache if there is one

### ISSUE THREAD

**Issue by kkinnear** [anmonteiro/lumo#82]
First, lumo is really great, I'm just getting started with it, but it is seriously fast and seems very stable.  Thanks for building it, looks like it was a lot of work!

I'm starting lumo 1.2.0 with this string
```clojure
lumo -k lumo_cache -c `lein classpath` -r
```
which is how I learned to start `planck`.  To start off I type `(require 'zprint.lumo)` to get my namespace loaded and everything is good.  However, if I then change `src/zprint/lumo.cljc` and go to the repl and type 
```clojure
(require 'zprint.lumo :reload)
```
 it doesn't reload the namespace with the changes in it.  If I then type
```clojure
rm lumo_cache/*lumo*
```
at a shell, and then go back to the repl and type
```clojure
(require 'zprint.lumo :reload)
```
then my namespace is reloaded.

Perhaps I'm missing something, but I expected the namespace to be reloaded regardless of whether it appeared in the cache or not.  This isn't a time critical problem, as there is a perfectly good workaround.  If I had to reload everything each time I made a change, I'd be in trouble (as it takes minutes to compile), but the workaround is not taxing.  Still, it would be nice if it just worked.

Thanks!

**Comment by anmonteiro** [comment]
I think I know what you want, and I feel like I outlined it in https://github.com/anmonteiro/lumo/issues/54#issuecomment-271873541

**Comment by kkinnear** [comment]
I looked around, but I missed that discussion.  I'll comment further over there.  Thanks!

**Comment by anmonteiro** [comment]
Discussion in #54
