### ISSUE TITLE
Package management

### ISSUE THREAD

**Issue by jeaye** [anmonteiro/lumo#9]
Any plans of officially integrating with MacOS's homebrew, Arch's AUR, etc? I'm very excited about a faster REPL (takes 16 seconds to start `lein repl` on my machine) and I think a quick and familiar installation would help bring in new users.

**Comment by arichiardi** [comment]
Note that the `lein repl` is an `nRepl` which historically is has the best support for tooling. Just saying. If we can actually integrate `lumo` with existing stuff (`cider` ?) it would be really great but I see it tough.

@anmonteiro are you using [inf-clojure](https://github.com/clojure-emacs/inf-clojure) with `lumo` for working on projects?

**Comment by anmonteiro** [comment]
@jeaye I'm interested in uploading Lumo artifacts to package managers, I think it'll facilitate adoption. I just didn't get around to doing it yet.

@arichiardi I'm planning to add support for a Socket REPL, just like Planck [has](http://planck-repl.org/socket-repl.html). Implementing the nREPL protocol is not something I have planned, though, and I'm not sure it even makes sense.

**Comment by anmonteiro** [comment]
From #20: [basic instructions for adding a Homebrew formula](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#basic-instructions)

**Comment by leppert** [comment]
Homebrew formula submitted https://github.com/Homebrew/homebrew-core/pull/6885

**Comment by anmonteiro** [comment]
@leppert this might be the result of my ignorance about how Homebrew works, but will the Brew formula run `boot release` for every installation? That's a concern because it takes >20 minutes on an empty cache.
If the above is true, could we somehow make it grab the `lumo_mac.zip` from the release, unzip it and install that?

**Comment by leppert** [comment]
@anmonteiro I'm rather new to it as well, but I believe once the formula is accepted a bot will autogenerate "bottles" for each of the dominate OS versions. See here:
https://github.com/Homebrew/brew/blob/master/docs/Bottles.md#bottle-creation

And here's what it looks like when the bot commits:
https://github.com/Homebrew/homebrew-core/commit/7dce27433f2f4542048b4fdd81aaf12e8a115bd9

**Comment by anmonteiro** [comment]
As of 1.0.0-alpha3, there is now a [NPM package](https://www.npmjs.com/package/lumo-cljs) for Lumo. You can install it via `npm install -g lumo-cljs`

**Comment by jiyinyiyong** [comment]
```
> lumo-cljs@1.0.0-alpha3 install /usr/local/lib/node_modules/lumo-cljs
> node scripts/npm_install.js
```

**Comment by anmonteiro** [comment]
@jiyinyiyong it downloads about 11MB (the zipped Lumo binary). did the installation fail for you?

**Comment by jiyinyiyong** [comment]
No, but I killed it. I download latest release from GitHub with Chrome and that turned out to be faster. So I killed it and used the binary. Is there a way to show the progress bar since it's downloading slowly like [this](https://www.npmjs.com/package/progress)?

**Comment by anmonteiro** [comment]
I'm not going to spend any time doing it but feel free to implement it yourself. the script is here: https://github.com/anmonteiro/lumo/blob/master/packages/lumo/scripts/npm_install.js

**Comment by jiyinyiyong** [comment]
Try this https://github.com/anmonteiro/lumo/pull/47

**Comment by anmonteiro** [comment]
Lumo is currently deployed to NPM and Homebrew. Would anyone like to see it in other package managers? I'm inclined to close this, I think we solved the immediate problem.

**Comment by jiyinyiyong** [comment]
I need it in Ubuntu since sometimes I want compile my script with it. But npm package could be fine in this case, if I can install it correctly.

**Comment by anmonteiro** [comment]
Closing this for now, please open individual issues if you want to see Lumo deployed to any other package managers.
