### ISSUE TITLE
Completions should not return a javascript object?

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#91]
Hello Antonio!

I am playing with a `lumo-mode` for emacs and I was wondering if there is a reason why `lumo.repl/get-completions` return a `#js {}`. It is kind of not good, performance-wise, to always convert to list of strings here.

I can issue a PR that changes that of course, but I wanted to ask first because there might be a good use case for it.

Thanks!

**Comment by anmonteiro** [comment]
They need to return a JS object because we feed them into Node.js's `readline`.
