### ISSUE TITLE
build fails (missing dep?)

### ISSUE THREAD

**Issue by rpodgorny** [anmonteiro/lumo#94]
when i try to build the git version i get:

```
Building production bundle with Browserify...
/home/radek/tmp/lumo/scripts/build.js:67
      throw err;
      ^

Error: Cannot find module 'require-from-string' from '/home/radek/tmp/lumo/src/js'
    at /home/radek/tmp/lumo/node_modules/resolve/lib/async.js:47:17
    at process (/home/radek/tmp/lumo/node_modules/resolve/lib/async.js:174:43)
    at ondir (/home/radek/tmp/lumo/node_modules/resolve/lib/async.js:189:17)
    at load (/home/radek/tmp/lumo/node_modules/resolve/lib/async.js:70:43)
    at onex (/home/radek/tmp/lumo/node_modules/resolve/lib/async.js:93:31)
    at /home/radek/tmp/lumo/node_modules/resolve/lib/async.js:23:47

```

**Comment by anmonteiro** [comment]
That's weird, as `require-from-string` is listed in the dependencies.
https://github.com/anmonteiro/lumo/blob/master/package.json#L28

**Comment by anmonteiro** [comment]
@rpodgorny In any case, I just regenerated the `yarn.lock` file. can you try a fresh clone and building again? 

Please report back. Thanks!

**Comment by rpodgorny** [comment]
hmmm, it works now for me after a clean checkout. it may have been some other problem, thou (i'm trying to solve the python/python2 issue).

thanks (closing)!
