### ISSUE TITLE
Handle duplicated dependency in Lumo 2 compiling cljs

### ISSUE THREAD

**Issue by jiyinyiyong** [anmonteiro/lumo#95]
I got strange logs in using compiling my existing project with lumo 2: https://github.com/mvc-works/stack-workflow/issues/1 I saw strange errors like:

```
WARNING: component? at line 6 is being replaced at line 6 respo/util/detect.cljc
WARNING: =seq at line 8 is being replaced at line 8 respo/util/detect.cljc
WARNING: element? at line 4 is being replaced at line 4 respo/util/detect.cljc
```

Last night I handled a case where `:test` dependency get in the way and replaced my real dependency. So I guess there might be similar problem in this case.

So I made small experiments to install packages at local, I got dependencies like `x->a2->a1` and `x->a3->a1` and during compilation I got this warning:

```
=>> lumo -Kc src/:$boot_deps -i build.cljs
WARNING: a1 at line 4 is being replaced at line 4 a1/main.cljs
```

Probably a bug here.

**Comment by anmonteiro** [comment]
Closing in favor or #245
