### ISSUE TITLE
When socket enabled, cannot eval at the prompt

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#97]
It works fine through the socket (using `inf-clojure`), but it hangs at the prompt:

![2017-03-07-170029_387x167_scrot](https://cloud.githubusercontent.com/assets/1724788/23685255/f0a1fcfa-0357-11e7-92b0-247f7766cebe.png)

This is on:
`Linux my-host 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

No a big deal, but better to track it.

**Comment by anmonteiro** [comment]
Can you try this with current master?

**Comment by arichiardi** [comment]
I will definitely try it out

**Comment by arichiardi** [comment]
Works on master with `inf-clojure` and `telnet`:

```
arichiardi@EP-LL-10020 ~$ telnet localhost 5555
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Lumo 1.3.0
ClojureScript 1.9.494
Node.js v7.8.0
 Docs: (doc function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=>
```

```
$ lumo -n 5555
Lumo 1.3.0
ClojureScript 1.9.494
Node.js v7.8.0
 Docs: (doc function-name-here)
 Exit: Control+D or :cljs/quit or exit

Lumo socket REPL listening at localhost:5555.
cljs.user=> (println "test")
test
nil
```

Closing and thanks a lot!
