### ISSUE TITLE
Does not resolve clojure.set

### ISSUE THREAD

**Issue by jiyinyiyong** [anmonteiro/lumo#98]
```
#error {:message "Invalid :refer, var clojure.set/union does not exist in file a3/main.cljs"
```

Demo code:

```clojure
(ns compile.main
  (:require
            [clojure.set :refer [union]]))

(.log js/console
  (union #{1} #{2}))
```

**Comment by anmonteiro** [comment]
can't repro here with latest master.

```
lumo main.cljs
{ meta: null,
  hash_map:
   { meta: null,
     cnt: 2,
     arr: [ 1, null, 2, null ],
     __hash: null,
     'cljs$lang$protocol_mask$partition0$': 16647951,
     'cljs$lang$protocol_mask$partition1$': 8196 },
  __hash: null,
  'cljs$lang$protocol_mask$partition0$': 15077647,
  'cljs$lang$protocol_mask$partition1$': 8196 }
```

**Comment by jiyinyiyong** [comment]
I cloned the repo and ran `npm i -g .` to install it. But still got this error. How do I install latest lumo correctly.

BTW I would suggest releasing on npm after every bug is fixed. The semantic version `major.minor.bugfix` was designed for that.

**Comment by anmonteiro** [comment]
To build Lumo, clone the repo, `yarn install` and `boot release`.

I don't want to release after every tiny fix, I prefer to maintain a coarser grained release schedule.

**Comment by jiyinyiyong** [comment]
Is it using a modified version of Node... ~20mins has past it's still compiling.

**Comment by jiyinyiyong** [comment]
Can you send me the latest binary you compiled?

**Comment by jiyinyiyong** [comment]
I downloaded the new binary and the error remains in https://github.com/jiyinyiyong/lumo-1.2-set-issue

```
=>> lumo -c src/ build.cljs
#error {:message "failed compiling file:out/cljs/core.cljs", :data {:file "out/cljs/core.cljs"}, :cause #error {:message "failed compiling file:/Users/chen/repo/jiyinyiyong/lumo-1.2-set-issue/src/demo/main.cljs", :data {:file "/Users/chen/repo/jiyinyiyong/lumo-1.2-set-issue/src/demo/main.cljs"}, :cause #error {:message "Could not analyze dep clojure.set", :data {:tag :cljs/analysis-error}, :cause #error {:message "Could not parse ns form demo.main", :data {:tag :cljs/analysis-error}, :cause #error {:message "Invalid :refer, var clojure.set/union does not exist", :data {:tag :cljs/analysis-error}}}}}}

=>> /Users/chen/Downloads/lumo -c src/ build.cljs
#error {:message "failed compiling file:out/cljs/core.cljs", :data {:file "out/cljs/core.cljs"}, :cause #error {:message "failed compiling file:/Users/chen/repo/jiyinyiyong/lumo-1.2-set-issue/src/demo/main.cljs", :data {:file "/Users/chen/repo/jiyinyiyong/lumo-1.2-set-issue/src/demo/main.cljs"}, :cause #error {:message "Could not analyze dep clojure.set", :data {:tag :cljs/analysis-error}, :cause #error {:message "Could not parse ns form demo.main", :data {:tag :cljs/analysis-error}, :cause #error {:message "Invalid :refer, var clojure.set/union does not exist", :data {:tag :cljs/analysis-error}}}}}}
```

It that possible there's problems in my environment. Does the binary depend on anything that's in my environment, which is different from yours?

**Comment by anmonteiro** [comment]
I haven't tried compiling a project that uses `clojure.set`. I'll get back to you when I have

**Comment by jiyinyiyong** [comment]
This issue blocked some of my plans. I think I got some time here. Is there anything I can do on my side if I'm trying to look into the problem?

**Comment by anmonteiro** [comment]
I haven't looked deeply into the issue, but my hunch is that there might be some conflict between Lumo's bound `cljs.env/*compiler*` and the one we set for compiling ClojureScript projects.

Ideally we want to have 2 different compilation environments there, which I'm not certain is the case currently.

**Comment by jiyinyiyong** [comment]
Sounds not like a good situation for me as it's not a simple bug. Going to dig into it anyway...
