### ISSUE TITLE
Repl outputs some hidden chars somehow

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#99]
Hi Antonio,

I know this report is very vague, but you can observe here that maybe some escape character, maybe due to the highlight, is off. Inf-clojure can understand ANSI colors the output and it does, but the format of these characters is not valid for it. Again, I am not an expert in the area therefore I am not sure.

![2017-03-05-194935_342x149_scrot](https://cloud.githubusercontent.com/assets/1724788/23765310/a585d8ea-04b5-11e7-95bb-ddb6b38da46c.png)

At the moment `inf-clojure` strips out the characters, but I wanted to open an issue because it might probably better to fix it here, if somebody has some suggestion on how to.

Thanks!

**Comment by arichiardi** [comment]
This is related to the node readline it seems:

http://stackoverflow.com/questions/21785955/messed-up-progress-bars-when-installing-npm-packages-inside-ansi-term

https://github.com/nodejs/node-v0.x-archive/issues/5344

So it seems that I can simply use the `-d` option for solving this problem.

**Comment by bolasblack** [comment]
Hey @arichiardi, I found you can use `(setq inf-clojure-program "lumo -d")` to make lumo stop print those character :)

**Comment by anmonteiro** [comment]
This is stilla bug. We should not output escape characters to the socket repl output

**Comment by anmonteiro** [comment]
Wait, so you don't need the socket REPL tonconnect to inf-clojure?!

**Comment by arichiardi** [comment]
Nope, the socket is just a convenience , the `inf-` modes are usually used to send to input and read from output descriptors.

**Comment by anmonteiro** [comment]
start Lumo with `--dumb` in inf-clojure, or TTY escape codes will be output
